// 미친맛집 (グルメな友達のグルメ店) 단어 데이터
const WORD_DATA_MIKMAT = {
  1: { title: "미친맛집 1화 - 마츠시게의 13년 단골", words: [
    {h:"いらっしゃいませ",r:"irasshaimase",m:"[인사] 어서 오세요"},
    {h:"ご無沙汰しております",r:"gobusata shite orimasu",m:"[인사] 오랜만입니다 (격식)"},
    {h:"久しぶり",r:"hisashiburi",m:"[인사] 오랜만이에요"},
    {h:"お待たせしました",r:"omatase shimashita",m:"[인사] 기다리셨습니다"},
    {h:"少々お待ちください",r:"shoushou omachi kudasai",m:"[인사] 잠시만 기다려주세요"},
    {h:"いただきます",r:"itadakimasu",m:"[인사] 잘 먹겠습니다"},
    {h:"かしこまりました",r:"kashikomarimashita",m:"[인사] 알겠습니다 (격식)"},
    {h:"乾杯",r:"kanpai",m:"[명] 건배"},
    {h:"番組",r:"bangumi",m:"[명] (TV) 프로그램"},
    {h:"焼き鳥",r:"yakitori",m:"[명] 닭꼬치/야키토리"},
    {h:"生ビール",r:"nama biiru",m:"[명] 생맥주"},
    {h:"山椒",r:"sanshou",m:"[명] 산초"},
    {h:"春雨",r:"harusame",m:"[명] 당면"},
    {h:"白菜",r:"hakusai",m:"[명] 배추"},
    {h:"豚肉",r:"butaniku",m:"[명] 돼지고기"},
    {h:"ニラ",r:"nira",m:"[명] 부추"},
    {h:"調味料",r:"choumiryou",m:"[명] 조미료"},
    {h:"具",r:"gu",m:"[명] (요리의) 속재료"},
    {h:"皮",r:"kawa",m:"[명] 피/껍질"},
    {h:"賄い",r:"makanai",m:"[명] 직원식/식사 제공"},
    {h:"予約",r:"yoyaku",m:"[명] 예약"},
    {h:"裏メニュー",r:"ura menyuu",m:"[명] 숨겨진 메뉴"},
    {h:"味",r:"aji",m:"[명] 맛"},
    {h:"舌",r:"shita",m:"[명] 혀"},
    {h:"うまい",r:"umai",m:"[이형] 맛있다 (구어)"},
    {h:"辛い",r:"karai",m:"[이형] 맵다"},
    {h:"くせになる",r:"kuse ni naru",m:"[표현] 중독되다/습관이 되다"},
    {h:"初めて",r:"hajimete",m:"[부] 처음으로"},
    {h:"本当に",r:"hontou ni",m:"[부] 정말로"},
    {h:"食べ比べる",r:"tabekuraberu",m:"[동] 먹어 비교하다"},
  ]},
  2: { title: "미친맛집 2화 - 일본에서 가장 비싼 치즈케이크", words: [
    {h:"景色",r:"keshiki",m:"[명] 경치/풍경"},
    {h:"小説家",r:"shousetsuka",m:"[명] 소설가"},
    {h:"文豪",r:"bungou",m:"[명] 대문호"},
    {h:"値段",r:"nedan",m:"[명] 가격/값"},
    {h:"結婚指輪",r:"kekkon yubiwa",m:"[명] 결혼반지"},
    {h:"女房",r:"nyoubou",m:"[명] 아내 (구어)"},
    {h:"仕事",r:"shigoto",m:"[명] 일/직업"},
    {h:"蒸し鶏",r:"mushi dori",m:"[명] 찜닭"},
    {h:"醤油",r:"shouyu",m:"[명] 간장"},
    {h:"ネギ",r:"negi",m:"[명] 파"},
    {h:"におい",r:"nioi",m:"[명] 냄새"},
    {h:"手袋",r:"tebukuro",m:"[명] 장갑"},
    {h:"おかず",r:"okazu",m:"[명] 반찬"},
    {h:"酸味",r:"sanmi",m:"[명] 산미/신맛"},
    {h:"すてき",r:"suteki",m:"[나형] 멋지다/근사하다"},
    {h:"爽やか",r:"sawayaka",m:"[나형] 상쾌하다"},
    {h:"まろやか",r:"maroyaka",m:"[나형] 부드럽다 (맛)"},
    {h:"充実",r:"juujitsu",m:"[나형] 충실하다/알차다"},
    {h:"嗅ぐ",r:"kagu",m:"[동] (냄새를) 맡다"},
    {h:"頑張る",r:"ganbaru",m:"[동] 힘내다/열심히 하다"},
    {h:"お邪魔する",r:"ojama suru",m:"[동] 방문하다 (겸양)"},
    {h:"間違える",r:"machigaeru",m:"[동] 틀리다/잘못하다"},
    {h:"さようでございます",r:"sayou de gozaimasu",m:"[표현] 그렇습니다 (최고 격식)"},
    {h:"気になる",r:"ki ni naru",m:"[표현] 궁금하다/신경 쓰이다"},
    {h:"白いご飯",r:"shiroi gohan",m:"[명] 흰밥/쌀밥"},
    {h:"ご飯のおかずにぴったり",r:"gohan no okazu ni pittari",m:"[표현] 밥반찬으로 딱이다"},
  ]},
};
