// 미친맛집 (グルメな友達のグルメ店) 단어 데이터
const WORD_DATA_MIKMAT = {
  1: { title: "1화 단어 (마츠시게의 13년 단골)", words: [
    // 명사
    {h:"グルメ",r:"gurume",m:"미식가/맛집"},
    {h:"友達",r:"tomodachi",m:"친구"},
    {h:"店",r:"mise",m:"가게"},
    {h:"コーヒー",r:"koohii",m:"커피"},
    {h:"ホット",r:"hotto",m:"따뜻한 (음료)"},
    {h:"番組",r:"bangumi",m:"(TV) 프로그램"},
    {h:"ファン",r:"fan",m:"팬"},
    {h:"おじさん",r:"ojisan",m:"아저씨"},
    {h:"乾杯",r:"kanpai",m:"건배"},
    {h:"国",r:"kuni",m:"나라"},
    {h:"味",r:"aji",m:"맛"},
    {h:"焼き鳥",r:"yakitori",m:"닭꼬치/야키토리"},
    {h:"焼き",r:"yaki",m:"구이"},
    {h:"揚げ",r:"age",m:"튀김"},
    {h:"調理法",r:"chourihou",m:"조리법"},
    {h:"裏メニュー",r:"ura menyuu",m:"숨겨진 메뉴"},
    {h:"調味料",r:"choumiryou",m:"조미료"},
    {h:"麻辣",r:"maara",m:"마라 (얼얼하고 매운 맛)"},
    {h:"辛み",r:"karami",m:"매운맛"},
    {h:"舌",r:"shita",m:"혀"},
    {h:"のど",r:"nodo",m:"목/목구멍"},
    {h:"口",r:"kuchi",m:"입"},
    {h:"冷菜",r:"reisai",m:"냉채/차가운 요리"},
    {h:"豆腐",r:"toufu",m:"두부"},
    {h:"担々麺",r:"tantanmen",m:"탄탄멘"},
    {h:"山椒",r:"sanshou",m:"산초"},
    {h:"生ビール",r:"nama biiru",m:"생맥주"},
    {h:"ノンアルコール",r:"non arukooru",m:"무알코올"},
    {h:"飲み物",r:"nomimono",m:"음료/마실 것"},
    {h:"マッコリ",r:"makkori",m:"막걸리"},
    {h:"組み合わせ",r:"kumiawase",m:"조합"},
    {h:"具",r:"gu",m:"(요리의) 속재료"},
    {h:"ニラ",r:"nira",m:"부추"},
    {h:"豚肉",r:"butaniku",m:"돼지고기"},
    {h:"皮",r:"kawa",m:"피/껍질"},
    {h:"におい",r:"nioi",m:"냄새"},
    {h:"当日",r:"toujitsu",m:"당일"},
    {h:"春雨",r:"harusame",m:"당면"},
    {h:"白菜",r:"hakusai",m:"배추"},
    {h:"発酵",r:"hakkou",m:"발효"},
    {h:"味付け",r:"ajitsuke",m:"양념/간"},
    {h:"おかず",r:"okazu",m:"반찬"},
    {h:"賄い",r:"makanai",m:"직원식"},
    {h:"予約",r:"yoyaku",m:"예약"},
    {h:"雰囲気",r:"fun'iki",m:"분위기"},
    {h:"赤ちゃん",r:"akachan",m:"아기"},
    {h:"調子",r:"choushi",m:"컨디션/상태"},
    {h:"本場",r:"honba",m:"본고장/본장"},
    {h:"天秤棒",r:"tenbinbou",m:"지게/천칭봉"},
    // 동사
    {h:"食べる",r:"taberu",m:"먹다"},
    {h:"飲む",r:"nomu",m:"마시다"},
    {h:"行く",r:"iku",m:"가다"},
    {h:"言う",r:"iu",m:"말하다"},
    {h:"出る",r:"deru",m:"나오다/나가다"},
    {h:"使う",r:"tsukau",m:"쓰다/사용하다"},
    {h:"入れる",r:"ireru",m:"넣다"},
    {h:"作る",r:"tsukuru",m:"만들다"},
    {h:"変わる",r:"kawaru",m:"변하다/달라지다"},
    {h:"飛ぶ",r:"tobu",m:"날다/튀다"},
    {h:"焦げる",r:"kogeru",m:"타다/눋다"},
    {h:"覚える",r:"oboeru",m:"외우다/기억하다"},
    {h:"売り歩く",r:"uriaruku",m:"돌아다니며 팔다"},
    {h:"担ぐ",r:"katsugu",m:"메다/짊어지다"},
    {h:"取り分ける",r:"toriwakeru",m:"나눠 담다"},
    {h:"食べ比べる",r:"tabekuraberu",m:"먹어 비교하다"},
    {h:"語り合う",r:"katariau",m:"이야기를 나누다"},
    // 형용사·부사
    {h:"うまい",r:"umai",m:"맛있다 (구어)"},
    {h:"おいしい",r:"oishii",m:"맛있다"},
    {h:"辛い",r:"karai",m:"맵다"},
    {h:"楽しい",r:"tanoshii",m:"즐겁다"},
    {h:"面白い",r:"omoshiroi",m:"재밌다"},
    {h:"楽",r:"raku",m:"편하다"},
    {h:"やばい",r:"yabai",m:"대박/미쳤다"},
    {h:"本当に",r:"hontou ni",m:"정말로"},
    {h:"初めて",r:"hajimete",m:"처음으로"},
    {h:"久々に",r:"hisabisa ni",m:"오랜만에"},
    {h:"ぜひ",r:"zehi",m:"꼭/반드시"},
    {h:"結構",r:"kekkou",m:"꽤/상당히"},
    {h:"全部",r:"zenbu",m:"전부/다"},
    {h:"ちゃんと",r:"chanto",m:"제대로/똑바로"},
    {h:"ヒリヒリ",r:"hirihiri",m:"얼얼하게/따끔따끔"},
  ]},
  2: { title: "1화 표현 (마츠시게의 13년 단골)", words: [
    {h:"いらっしゃいませ",r:"irasshaimase",m:"어서 오세요"},
    {h:"かしこまりました",r:"kashikomarimashita",m:"알겠습니다 (격식)"},
    {h:"少々お待ちください",r:"shoushou omachi kudasai",m:"잠시만 기다려주세요"},
    {h:"こんにちは",r:"konnichiwa",m:"안녕하세요"},
    {h:"ご無沙汰しております",r:"gobusata shite orimasu",m:"오랜만입니다 (격식)"},
    {h:"久しぶり",r:"hisashiburi",m:"오랜만이에요"},
    {h:"お待たせしました",r:"omatase shimashita",m:"기다리셨습니다"},
    {h:"ありがとう",r:"arigatou",m:"감사합니다"},
    {h:"よろしくお願いします",r:"yoroshiku onegai shimasu",m:"잘 부탁드립니다"},
    {h:"いただきます",r:"itadakimasu",m:"잘 먹겠습니다"},
    {h:"そうですね",r:"sou desu ne",m:"그렇죠"},
    {h:"ですよね",r:"desu yo ne",m:"그렇죠?/맞죠?"},
    {h:"じゃあ 行きましょう",r:"jaa ikimashou",m:"그럼 가시죠"},
    {h:"これ 使ってください",r:"kore tsukatte kudasai",m:"이거 쓰세요"},
    {h:"食べたことないから",r:"tabeta koto nai kara",m:"먹어본 적 없어서"},
    {h:"どれがいいかな",r:"dore ga ii kana",m:"어떤 게 좋을까"},
    {h:"辛いものってどのぐらいいけるんですか",r:"karai mono tte dono gurai ikerun desu ka",m:"매운 거 어느 정도 드세요?"},
    {h:"くせになっちゃった",r:"kuse ni nacchatta",m:"중독되어 버렸어"},
    {h:"具は何ですか",r:"gu wa nan desu ka",m:"속재료가 뭐예요?"},
    {h:"大丈夫？",r:"daijoubu?",m:"괜찮아?"},
    {h:"何か飲む？",r:"nanika nomu?",m:"뭐 마실래?"},
    {h:"生ビールもらってもいいですか",r:"nama biiru moratte mo ii desu ka",m:"생맥주 주문해도 될까요?"},
    {h:"飲み過ぎて",r:"nomi sugite",m:"너무 많이 마셔서"},
    {h:"入れすぎ",r:"iresugi",m:"너무 많이 넣었어"},
    {h:"味が変わる",r:"aji ga kawaru",m:"맛이 변하다"},
    {h:"味が出る",r:"aji ga deru",m:"제맛이 나다"},
    {h:"いいおかずになる",r:"ii okazu ni naru",m:"좋은 반찬이 되다"},
    {h:"あったまりそう",r:"attamari sou",m:"따뜻해질 것 같다"},
    {h:"初めての味だ",r:"hajimete no aji da",m:"처음인 맛이야"},
    {h:"予約をしたほうがいい",r:"yoyaku wo shita hou ga ii",m:"예약을 하는 편이 좋다"},
    {h:"やばい雰囲気になってきた",r:"yabai fun'iki ni natte kita",m:"위험한 분위기가 되고 있어"},
    {h:"調子がよくなる",r:"choushi ga yoku naru",m:"컨디션이 좋아지다"},
    {h:"食べ比べてみたい",r:"tabekurabete mitai",m:"먹어 비교해보고 싶다"},
    {h:"食べて語り合えば",r:"tabete katariaeba",m:"먹으면서 이야기를 나누면"},
    {h:"僕の番組にぜひ出てほしい",r:"boku no bangumi ni zehi dete hoshii",m:"내 프로그램에 꼭 나와줬으면"},
    {h:"のどにカーッと",r:"nodo ni kaatto",m:"목에 화악 하고"},
    {h:"皮の味が変わる",r:"kawa no aji ga kawaru",m:"껍질 맛이 달라지다"},
    {h:"賄いなんだ",r:"makanai nanda",m:"직원식이구나"},
  ]},
  3: { title: "2화 단어 (일본에서 가장 비싼 치즈케이크)", words: [
    // 명사
    {h:"鎌倉",r:"kamakura",m:"가마쿠라 (지명)"},
    {h:"駅",r:"eki",m:"역"},
    {h:"景色",r:"keshiki",m:"경치/풍경"},
    {h:"昔",r:"mukashi",m:"옛날/예전"},
    {h:"文豪",r:"bungou",m:"대문호"},
    {h:"小説家",r:"shousetsuka",m:"소설가"},
    {h:"文化人",r:"bunkajin",m:"문화인"},
    {h:"秋",r:"aki",m:"가을"},
    {h:"チョコレートケーキ",r:"chokoreto keeki",m:"초콜릿케이크"},
    {h:"チーズケーキ",r:"chiizu keeki",m:"치즈케이크"},
    {h:"うわさ",r:"uwasa",m:"소문/평판"},
    {h:"値段",r:"nedan",m:"가격/값"},
    {h:"サイズ",r:"saizu",m:"사이즈/크기"},
    {h:"ホール",r:"hooru",m:"홀/통째"},
    {h:"かき氷",r:"kakigoori",m:"빙수"},
    {h:"マンゴー",r:"mangoo",m:"망고"},
    {h:"ワイン",r:"wain",m:"와인"},
    {h:"貴腐ワイン",r:"kifu wain",m:"귀부 와인"},
    {h:"腐敗",r:"fuhai",m:"부패"},
    {h:"カビ",r:"kabi",m:"곰팡이"},
    {h:"実",r:"mi",m:"열매"},
    {h:"サワークリーム",r:"sawaa kuriimu",m:"사워크림"},
    {h:"クリームチーズ",r:"kuriimu chiizu",m:"크림치즈"},
    {h:"クラッカー",r:"kurakkaa",m:"크래커"},
    {h:"酸味",r:"sanmi",m:"산미/신맛"},
    {h:"結婚指輪",r:"kekkon yubiwa",m:"결혼반지"},
    {h:"女房",r:"nyoubou",m:"아내 (구어)"},
    {h:"仕事",r:"shigoto",m:"일/직업"},
    {h:"名前",r:"namae",m:"이름"},
    {h:"スペアリブ",r:"supea ribu",m:"스페어리브"},
    {h:"蒸し鶏",r:"mushi dori",m:"찜닭/쪄낸 닭"},
    {h:"ネギ",r:"negi",m:"파"},
    {h:"醤油",r:"shouyu",m:"간장"},
    {h:"手袋",r:"tebukuro",m:"장갑"},
    {h:"ご飯",r:"gohan",m:"밥"},
    {h:"おかず",r:"okazu",m:"반찬"},
    {h:"部位",r:"bui",m:"부위"},
    {h:"お礼",r:"orei",m:"감사/답례"},
    {h:"兄さん",r:"niisan",m:"형/오빠"},
    {h:"オオカミ",r:"ookami",m:"늑대"},
    {h:"一匹",r:"ippiki",m:"한 마리"},
    // 동사
    {h:"暮らす",r:"kurasu",m:"살다/거주하다"},
    {h:"来る",r:"kuru",m:"오다"},
    {h:"入る",r:"hairu",m:"들어가다"},
    {h:"座る",r:"suwaru",m:"앉다"},
    {h:"合う",r:"au",m:"맞다/어울리다"},
    {h:"嗅ぐ",r:"kagu",m:"(냄새를) 맡다"},
    {h:"泣く",r:"naku",m:"울다"},
    {h:"のせる",r:"noseru",m:"올리다/얹다"},
    {h:"頑張る",r:"ganbaru",m:"힘내다/열심히 하다"},
    {h:"間違える",r:"machigaeru",m:"틀리다/잘못하다"},
    {h:"お邪魔する",r:"ojama suru",m:"방문하다 (겸양)"},
    {h:"分かる",r:"wakaru",m:"알다/이해하다"},
    // 형용사·부사
    {h:"すてき",r:"suteki",m:"멋지다/근사하다"},
    {h:"爽やか",r:"sawayaka",m:"상쾌하다"},
    {h:"まろやか",r:"maroyaka",m:"부드럽다 (맛)"},
    {h:"甘い",r:"amai",m:"달다"},
    {h:"白い",r:"shiroi",m:"하얀/흰"},
    {h:"大きい",r:"ookii",m:"크다"},
    {h:"小さい",r:"chiisai",m:"작다"},
    {h:"細い",r:"hosoi",m:"가늘다/얇다"},
    {h:"強い",r:"tsuyoi",m:"강하다/진심이다"},
    {h:"充実",r:"juujitsu",m:"충실하다/알차다"},
    {h:"非常に",r:"hijou ni",m:"매우/대단히"},
    {h:"すごく",r:"sugoku",m:"엄청/매우"},
    {h:"シャリシャリ",r:"sharishari",m:"바삭바삭/아삭아삭"},
    {h:"ずっと",r:"zutto",m:"계속/쭉"},
  ]},
  4: { title: "2화 표현 (일본에서 가장 비싼 치즈케이크)", words: [
    {h:"いらっしゃいませ",r:"irasshaimase",m:"어서 오세요"},
    {h:"ありがとうございます",r:"arigatou gozaimasu",m:"감사합니다 (격식)"},
    {h:"すみません",r:"sumimasen",m:"실례합니다/죄송합니다"},
    {h:"お願いします",r:"onegai shimasu",m:"부탁합니다"},
    {h:"さようでございます",r:"sayou de gozaimasu",m:"그렇습니다 (최고 격식)"},
    {h:"初めて来ました",r:"hajimete kimashita",m:"처음 왔습니다"},
    {h:"すごいでしょ",r:"sugoi desho",m:"대단하죠?/멋지죠?"},
    {h:"すてきだな",r:"suteki da na",m:"멋지다/근사하네"},
    {h:"ここだけ秋だ",r:"koko dake aki da",m:"여기만 가을이야"},
    {h:"これはチョコレートケーキ？",r:"kore wa chokoreto keeki?",m:"이건 초콜릿케이크?"},
    {h:"これがうわさのチーズケーキ",r:"kore ga uwasa no chiizu keeki",m:"이게 소문의 치즈케이크"},
    {h:"値段間違えてませんよね",r:"nedan machigaetemsen yo ne",m:"가격 틀린 거 아니죠?"},
    {h:"ホールのお取り扱いになっております",r:"hooru no otoriatsukai ni natte orimasu",m:"홀 케이크 기준입니다"},
    {h:"こちらへ",r:"kochira e",m:"이쪽으로"},
    {h:"お邪魔して",r:"ojama shite",m:"방문해서/찾아뵙고"},
    {h:"女房と２人で",r:"nyoubou to futari de",m:"아내와 둘이서"},
    {h:"セットとさせていただきます",r:"setto to sasete itadakimasu",m:"세트로 하겠습니다"},
    {h:"チーズケーキに合うように",r:"chiizu keeki ni au you ni",m:"치즈케이크에 맞게"},
    {h:"充実してるじゃないですか",r:"juujitsu shiteru ja nai desu ka",m:"알차지 않습니까"},
    {h:"味が気になる",r:"aji ga ki ni naru",m:"맛이 궁금하다"},
    {h:"においを嗅ぐ",r:"nioi wo kagu",m:"냄새를 맡다"},
    {h:"好きにすればいいんじゃないの",r:"suki ni sureba iin ja nai no",m:"좋을 대로 하면 되지 않아?"},
    {h:"チーズの酸味とまろやかさの中に",r:"chiizu no sanmi to maroyakasa no naka ni",m:"치즈의 산미와 부드러움 속에"},
    {h:"仕事のことばかり",r:"shigoto no koto bakari",m:"일 생각뿐"},
    {h:"そりゃ泣くことじゃない",r:"sorya naku koto ja nai",m:"그건 울 일이 아니야"},
    {h:"入りましょう",r:"hairimashou",m:"들어가 보시죠"},
    {h:"頑張って作りますんで",r:"ganbatte tsukurimasun de",m:"열심히 만들겠습니다"},
    {h:"白いご飯の上にのせて食べるべき",r:"shiroi gohan no ue ni nosete taberu beki",m:"흰밥 위에 올려서 먹어야 해"},
    {h:"ご飯のおかずにぴったり",r:"gohan no okazu ni pittari",m:"밥반찬으로 딱이다"},
    {h:"手袋をして食べてください",r:"tebukuro wo shite tabete kudasai",m:"장갑을 끼고 드세요"},
    {h:"お礼を言いたい",r:"orei wo iitai",m:"감사 인사를 하고 싶다"},
    {h:"分かるでしょ",r:"wakaru desho",m:"알겠지?/알지?"},
  ]},
};
