// 중급 일본어 단어 데이터
const WORD_DATA_INTERMEDIATE = {
  1: { title: "감정·상태", words: [
    {h:"うれしい",r:"ureshii",m:"[이형] 기쁘다"},
    {h:"かなしい",r:"kanashii",m:"[이형] 슬프다"},
    {h:"さびしい",r:"sabishii",m:"[이형] 외롭다"},
    {h:"くやしい",r:"kuyashii",m:"[이형] 분하다"},
    {h:"はずかしい",r:"hazukashii",m:"[이형] 부끄럽다"},
    {h:"こわい",r:"kowai",m:"[이형] 무섭다"},
    {h:"つまらない",r:"tsumaranai",m:"[이형] 지루하다"},
    {h:"なつかしい",r:"natsukashii",m:"[이형] 그립다"},
    {h:"うらやましい",r:"urayamashii",m:"[이형] 부럽다"},
    {h:"くるしい",r:"kurushii",m:"[이형] 괴롭다"},
    {h:"つらい",r:"tsurai",m:"[이형] 힘들다/고되다"},
    {h:"しんぱい",r:"shinpai",m:"[나형] 걱정"},
    {h:"あんしん",r:"anshin",m:"[나형] 안심"},
    {h:"びっくり",r:"bikkuri",m:"[부] 깜짝"},
    {h:"がっかり",r:"gakkari",m:"[부] 실망"},
  ]},
  2: { title: "직장·비즈니스", words: [
    {h:"かいしゃ",r:"kaisha",m:"[명] 회사"},
    {h:"しごと",r:"shigoto",m:"[명] 일/직업"},
    {h:"かいぎ",r:"kaigi",m:"[명] 회의"},
    {h:"しゅっちょう",r:"shucchou",m:"[명] 출장"},
    {h:"きゅうりょう",r:"kyuuryou",m:"[명] 급료/월급"},
    {h:"じょうし",r:"joushi",m:"[명] 상사"},
    {h:"ぶか",r:"buka",m:"[명] 부하"},
    {h:"どうりょう",r:"douryou",m:"[명] 동료"},
    {h:"けいやく",r:"keiyaku",m:"[명] 계약"},
    {h:"しめきり",r:"shimekiri",m:"[명] 마감"},
    {h:"ざんぎょう",r:"zangyou",m:"[명] 야근/잔업"},
    {h:"めいし",r:"meishi",m:"[명] 명함"},
    {h:"はたらく",r:"hataraku",m:"[동] 일하다"},
    {h:"やめる",r:"yameru",m:"[동] 그만두다"},
    {h:"つとめる",r:"tsutomeru",m:"[동] 근무하다"},
  ]},
};
