// 미친맛집 시즌1 - 2화
WORD_DATA_MIKMAT[3] = { title: "2화 단어 (일본에서 가장 비싼 치즈케이크)", words: [
    // 명사
    {h:"かまくら",k:"鎌倉",r:"kamakura",m:"가마쿠라 (지명)"},
    {h:"えき",k:"駅",r:"eki",m:"역"},
    {h:"けしき",k:"景色",r:"keshiki",m:"경치/풍경"},
    {h:"むかし",k:"昔",r:"mukashi",m:"옛날/예전"},
    {h:"ぶんごう",k:"文豪",r:"bungou",m:"대문호"},
    {h:"しょうせつか",k:"小説家",r:"shousetsuka",m:"소설가"},
    {h:"ぶんかじん",k:"文化人",r:"bunkajin",m:"문화인"},
    {h:"あき",k:"秋",r:"aki",m:"가을"},
    {h:"チョコレートケーキ",r:"chokoreto keeki",m:"초콜릿케이크"},
    {h:"チーズケーキ",r:"chiizu keeki",m:"치즈케이크"},
    {h:"うわさ",r:"uwasa",m:"소문/평판"},
    {h:"ねだん",k:"値段",r:"nedan",m:"가격/값"},
    {h:"サイズ",r:"saizu",m:"사이즈/크기"},
    {h:"ホール",r:"hooru",m:"홀/통째"},
    {h:"かきごおり",k:"かき氷",r:"kakigoori",m:"빙수"},
    {h:"マンゴー",r:"mangoo",m:"망고"},
    {h:"ワイン",r:"wain",m:"와인"},
    {h:"きふワイン",k:"貴腐ワイン",r:"kifu wain",m:"귀부 와인"},
    {h:"ふはい",k:"腐敗",r:"fuhai",m:"부패"},
    {h:"カビ",r:"kabi",m:"곰팡이"},
    {h:"み",k:"実",r:"mi",m:"열매"},
    {h:"サワークリーム",r:"sawaa kuriimu",m:"사워크림"},
    {h:"クリームチーズ",r:"kuriimu chiizu",m:"크림치즈"},
    {h:"クラッカー",r:"kurakkaa",m:"크래커"},
    {h:"さんみ",k:"酸味",r:"sanmi",m:"산미/신맛"},
    {h:"けっこんゆびわ",k:"結婚指輪",r:"kekkon yubiwa",m:"결혼반지"},
    {h:"にょうぼう",k:"女房",r:"nyoubou",m:"아내 (구어)"},
    {h:"しごと",k:"仕事",r:"shigoto",m:"일/직업"},
    {h:"なまえ",k:"名前",r:"namae",m:"이름"},
    {h:"スペアリブ",r:"supea ribu",m:"스페어리브"},
    {h:"むしどり",k:"蒸し鶏",r:"mushi dori",m:"찜닭/쪄낸 닭"},
    {h:"ネギ",r:"negi",m:"파"},
    {h:"しょうゆ",k:"醤油",r:"shouyu",m:"간장"},
    {h:"てぶくろ",k:"手袋",r:"tebukuro",m:"장갑"},
    {h:"ごはん",k:"ご飯",r:"gohan",m:"밥"},
    {h:"おかず",r:"okazu",m:"반찬"},
    {h:"ぶい",k:"部位",r:"bui",m:"부위"},
    {h:"おれい",k:"お礼",r:"orei",m:"감사/답례"},
    {h:"にいさん",k:"兄さん",r:"niisan",m:"형/오빠"},
    {h:"オオカミ",r:"ookami",m:"늑대"},
    {h:"いっぴき",k:"一匹",r:"ippiki",m:"한 마리"},
    // 동사
    {h:"くらす",k:"暮らす",r:"kurasu",m:"살다/거주하다"},
    {h:"くる",k:"来る",r:"kuru",m:"오다"},
    {h:"はいる",k:"入る",r:"hairu",m:"들어가다"},
    {h:"すわる",k:"座る",r:"suwaru",m:"앉다"},
    {h:"あう",k:"合う",r:"au",m:"맞다/어울리다"},
    {h:"かぐ",k:"嗅ぐ",r:"kagu",m:"(냄새를) 맡다"},
    {h:"なく",k:"泣く",r:"naku",m:"울다"},
    {h:"のせる",r:"noseru",m:"올리다/얹다"},
    {h:"がんばる",k:"頑張る",r:"ganbaru",m:"힘내다/열심히 하다"},
    {h:"まちがえる",k:"間違える",r:"machigaeru",m:"틀리다/잘못하다"},
    {h:"おじゃまする",k:"お邪魔する",r:"ojama suru",m:"방문하다 (겸양)"},
    {h:"わかる",k:"分かる",r:"wakaru",m:"알다/이해하다"},
    // 형용사·부사
    {h:"すてき",r:"suteki",m:"멋지다/근사하다"},
    {h:"さわやか",k:"爽やか",r:"sawayaka",m:"상쾌하다"},
    {h:"まろやか",r:"maroyaka",m:"부드럽다 (맛)"},
    {h:"あまい",k:"甘い",r:"amai",m:"달다"},
    {h:"しろい",k:"白い",r:"shiroi",m:"하얀/흰"},
    {h:"おおきい",k:"大きい",r:"ookii",m:"크다"},
    {h:"ちいさい",k:"小さい",r:"chiisai",m:"작다"},
    {h:"ほそい",k:"細い",r:"hosoi",m:"가늘다/얇다"},
    {h:"つよい",k:"強い",r:"tsuyoi",m:"강하다/진심이다"},
    {h:"じゅうじつ",k:"充実",r:"juujitsu",m:"충실하다/알차다"},
    {h:"ひじょうに",k:"非常に",r:"hijou ni",m:"매우/대단히"},
    {h:"すごく",r:"sugoku",m:"엄청/매우"},
    {h:"シャリシャリ",r:"sharishari",m:"바삭바삭/아삭아삭"},
    {h:"ずっと",r:"zutto",m:"계속/쭉"},
  ];
WORD_DATA_MIKMAT[4] = { title: "2화 표현 (일본에서 가장 비싼 치즈케이크)", words: [
    {h:"いらっしゃいませ",r:"irasshaimase",m:"어서 오세요"},
    {h:"ありがとうございます",r:"arigatou gozaimasu",m:"감사합니다 (격식)"},
    {h:"すみません",r:"sumimasen",m:"실례합니다/죄송합니다"},
    {h:"お願いします",r:"onegai shimasu",m:"부탁합니다"},
    {h:"さようでございます",r:"sayou de gozaimasu",m:"그렇습니다 (최고 격식)"},
    {h:"初めて来ました",r:"hajimete kimashita",m:"처음 왔습니다"},
    {h:"すごいでしょ",r:"sugoi desho",m:"대단하죠?/멋지죠?"},
    {h:"すてきだな",r:"suteki da na",m:"멋지다/근사하네"},
    {h:"ここだけ秋だ",r:"koko dake aki da",m:"여기만 가을이야"},
    {h:"これはチョコレートケーキ？",r:"kore wa chokoreto keeki?",m:"이건 초콜릿케이크?"},
    {h:"これがうわさのチーズケーキ",r:"kore ga uwasa no chiizu keeki",m:"이게 소문의 치즈케이크"},
    {h:"値段間違えてませんよね",r:"nedan machigaetemsen yo ne",m:"가격 틀린 거 아니죠?"},
    {h:"ホールのお取り扱いになっております",r:"hooru no otoriatsukai ni natte orimasu",m:"홀 케이크 기준입니다"},
    {h:"こちらへ",r:"kochira e",m:"이쪽으로"},
    {h:"お邪魔して",r:"ojama shite",m:"방문해서/찾아뵙고"},
    {h:"女房と２人で",r:"nyoubou to futari de",m:"아내와 둘이서"},
    {h:"セットとさせていただきます",r:"setto to sasete itadakimasu",m:"세트로 하겠습니다"},
    {h:"チーズケーキに合うように",r:"chiizu keeki ni au you ni",m:"치즈케이크에 맞게"},
    {h:"充実してるじゃないですか",r:"juujitsu shiteru ja nai desu ka",m:"알차지 않습니까"},
    {h:"味が気になる",r:"aji ga ki ni naru",m:"맛이 궁금하다"},
    {h:"においを嗅ぐ",r:"nioi wo kagu",m:"냄새를 맡다"},
    {h:"好きにすればいいんじゃないの",r:"suki ni sureba iin ja nai no",m:"좋을 대로 하면 되지 않아?"},
    {h:"チーズの酸味とまろやかさの中に",r:"chiizu no sanmi to maroyakasa no naka ni",m:"치즈의 산미와 부드러움 속에"},
    {h:"仕事のことばかり",r:"shigoto no koto bakari",m:"일 생각뿐"},
    {h:"そりゃ泣くことじゃない",r:"sorya naku koto ja nai",m:"그건 울 일이 아니야"},
    {h:"入りましょう",r:"hairimashou",m:"들어가 보시죠"},
    {h:"頑張って作りますんで",r:"ganbatte tsukurimasun de",m:"열심히 만들겠습니다"},
    {h:"白いご飯の上にのせて食べるべき",r:"shiroi gohan no ue ni nosete taberu beki",m:"흰밥 위에 올려서 먹어야 해"},
    {h:"ご飯のおかずにぴったり",r:"gohan no okazu ni pittari",m:"밥반찬으로 딱이다"},
    {h:"手袋をして食べてください",r:"tebukuro wo shite tabete kudasai",m:"장갑을 끼고 드세요"},
    {h:"お礼を言いたい",r:"orei wo iitai",m:"감사 인사를 하고 싶다"},
    {h:"分かるでしょ",r:"wakaru desho",m:"알겠지?/알지?"},
  ];
