// 미친맛집 시즌1 - 3화
WORD_DATA_MIKMAT[5] = { title: "3화 단어 (눈물 나는 맛, 레전드 야키니쿠)", words: [
    // 명사
    {h:"やきにく",k:"焼肉",r:"yakiniku",m:"야키니쿠/구운 고기"},
    {h:"しもふり",k:"霜降り",r:"shimofuri",m:"마블링/서리내림 (고기)"},
    {h:"ロース",r:"roosu",m:"등심/로스"},
    {h:"ごくじょう",k:"極上",r:"gokujou",m:"최상급/극상"},
    {h:"カルビ",r:"karubi",m:"갈비"},
    {h:"コプチャン",r:"kopuchan",m:"곱창"},
    {h:"シビレ",r:"shibire",m:"흉선 (야키니쿠 부위)"},
    {h:"ジンギスカン",r:"jingisukan",m:"징기스칸 (양고기 BBQ)"},
    {h:"さんまいにく",k:"三枚肉",r:"sanmainiku",m:"삼겹살"},
    {h:"しぼう",k:"脂肪",r:"shibou",m:"지방"},
    {h:"あみ",k:"網",r:"ami",m:"석쇠/그릴망"},
    {h:"キャベツ",r:"kyabetsu",m:"양배추"},
    {h:"ポッサム",r:"possamu",m:"보쌈"},
    {h:"おおジョッキ",k:"大ジョッキ",r:"oo jokki",m:"대형 맥주잔"},
    {h:"たれ",r:"tare",m:"양념장/소스"},
    {h:"あまみ",k:"甘み",r:"amami",m:"단맛"},
    {h:"しおけ",k:"塩気",r:"shioke",m:"짠맛"},
    {h:"ちょうわ",k:"調和",r:"chouwa",m:"조화"},
    {h:"かんばんメニュー",k:"看板メニュー",r:"kanban menyuu",m:"간판 메뉴/대표 메뉴"},
    {h:"はんライス",k:"半ライス",r:"han raisu",m:"반공기 (밥)"},
    {h:"たんさんすい",k:"炭酸水",r:"tansansui",m:"탄산수"},
    {h:"きょうせん",k:"胸腺",r:"kyousen",m:"흉선"},
    {h:"いっしゅん",k:"一瞬",r:"isshun",m:"순간/찰나"},
    {h:"かくげん",k:"格言",r:"kakugen",m:"격언"},
    // 동사
    {h:"かしきる",k:"貸し切る",r:"kashikiru",m:"전세 내다/전부 빌리다"},
    {h:"やく",k:"焼く",r:"yaku",m:"굽다"},
    {h:"まく",k:"巻く",r:"maku",m:"말다/감다"},
    {h:"めしあがる",k:"召し上がる",r:"meshiagaru",m:"드시다 (존경어)"},
    // 형용사·부사
    {h:"あつい",k:"熱い",r:"atsui",m:"뜨겁다"},
    {h:"さびしい",k:"寂しい",r:"sabishii",m:"쓸쓸하다/외롭다"},
    {h:"ぜいたく",k:"贅沢",r:"zeitaku",m:"호화롭다/사치스럽다"},
    {h:"とりあえず",r:"toriaezu",m:"일단/우선"},
    {h:"ふしぎ",k:"不思議",r:"fushigi",m:"신기하다/불가사의하다"},
  ];
WORD_DATA_MIKMAT[6] = { title: "3화 표현 (눈물 나는 맛, 레전드 야키니쿠)", words: [
    {h:"店の一部を貸し切って撮影",r:"mise no ichibu wo kashikitte satsuei",m:"가게 일부를 빌려서 촬영"},
    {h:"前頼んだやつ食べたい",r:"mae tanonda yatsu tabetai",m:"전에 시킨 거 먹고 싶어"},
    {h:"カルビとコプチャンを召し上がりました",r:"karubi to kopuchan wo meshiagarimashita",m:"갈비와 곱창을 드셨어요"},
    {h:"とりあえずそれと極上霜降りロース",r:"toriaezu sore to gokujou shimofuri roosu",m:"일단 그것과 최상급 마블링 등심"},
    {h:"チャレンジしましょう",r:"charenji shimashou",m:"도전합시다"},
    {h:"焼肉は生を焼くんですよ",r:"yakiniku wa nama wo yakundsu yo",m:"야키니쿠는 생고기를 굽는 거예요"},
    {h:"脂肪 肉 脂肪みたいな",r:"shibou niku shibou mitai na",m:"지방, 살코기, 지방 같은"},
    {h:"当店一番人気のシビレになります",r:"touten ichiban ninki no shibire ni narimasu",m:"저희 가게 제일 인기 있는 시비레입니다"},
    {h:"一応看板メニューです",r:"ichiou kanban menyuu desu",m:"일단 간판 메뉴입니다"},
    {h:"たれは甘み塩気辛みが調和",r:"tare wa amami shioke karami ga chouwa",m:"양념장은 단맛·짠맛·매운맛이 조화"},
    {h:"巻いて食べるでしょ？",r:"maite taberu desho?",m:"싸서 먹죠?"},
    {h:"ご飯もらう？",r:"gohan morau?",m:"밥 시킬까?"},
    {h:"僕も半ライスで",r:"boku mo han raisu de",m:"저도 반공기로"},
    {h:"よく焼きが完成",r:"yoku yaki ga kansei",m:"웰던 완성"},
    {h:"網替えしますね",r:"amigae shimasu ne",m:"석쇠 교체할게요"},
    {h:"熱いのでお気をつけください",r:"atsui node oki wo tsuke kudasai",m:"뜨거우니 조심하세요"},
    {h:"不思議だ 初めてだ",r:"fushigi da hajimete da",m:"신기해, 처음이야"},
    {h:"時間との闘いだ",r:"jikan to no tatakai da",m:"시간과의 싸움이다"},
    {h:"肉のうまみも入ってるからね",r:"niku no umami mo haitteru kara ne",m:"고기 감칠맛도 들어있으니까"},
    {h:"炭酸水ってあります？",r:"tansansui tte arimasu?",m:"탄산수 있어요?"},
    {h:"一枚で四千ウォンだ",r:"ichimai de yonsen won da",m:"한 장에 4천 원이야"},
    {h:"極上 贅沢だよね",r:"gokujou zeitaku da yo ne",m:"최상급, 사치스럽지"},
    {h:"口にいる時間が一瞬だった",r:"kuchi ni iru jikan ga isshun datta",m:"입에 있는 시간이 찰나였어"},
  ];
