// 미친맛집 시즌1 - 4화
WORD_DATA_MIKMAT[7] = { title: "4화 단어 (최고의 술안주, 오마카세 야키토리)", words: [
    // 명사
    {h:"おさけ",k:"お酒",r:"osake",m:"술"},
    {h:"こくりゅう",k:"黒龍",r:"kokuryu",m:"코쿠류 (일본 술 이름)"},
    {h:"かぼちゃ",r:"kabocha",m:"단호박"},
    {h:"くじょうネギ",k:"九条ネギ",r:"kujou negi",m:"구조파 (교토 특산 파)"},
    {h:"すみそ",k:"酢味噌",r:"sumiso",m:"초된장"},
    {h:"さといも",k:"里芋",r:"satoimo",m:"토란"},
    {h:"にもの",k:"煮物",r:"nimono",m:"조림"},
    {h:"ガーリックバター",r:"gaarikku bataa",m:"갈릭버터"},
    {h:"ぎょうしゅく",k:"凝縮",r:"gyoushuku",m:"응축/농축"},
    {h:"おやこうこう",k:"親孝行",r:"oyakoukou",m:"효도"},
    {h:"りょうしん",k:"両親",r:"ryoushin",m:"부모님/양친"},
    {h:"ちょうちん",r:"chouchin",m:"초우친 (야키토리: 난황 꼬치)"},
    {h:"らんおう",k:"卵黄",r:"ran'ou",m:"난황/노른자"},
    {h:"らんかん",k:"卵管",r:"rankan",m:"난관/수란관"},
    {h:"くし",k:"串",r:"kushi",m:"꼬치"},
    {h:"ひざがしら",r:"hizagashira",m:"무릎 (야키토리 부위)"},
    {h:"なんこつ",k:"軟骨",r:"nankotsu",m:"연골"},
    {h:"きじょうゆ",k:"生醤油",r:"kijouyu",m:"생간장"},
    {h:"きゅうしゅう",k:"九州",r:"kyuushuu",m:"규슈 (지명)"},
    {h:"フライドチキン",r:"furaido chikin",m:"프라이드치킨"},
    {h:"にがみ",k:"苦み",r:"nigami",m:"쓴맛"},
    {h:"きしょう",k:"希少",r:"kishou",m:"희귀한/드문"},
    {h:"わ",k:"羽",r:"wa",m:"~마리 (새 세는 단위)"},
    {h:"みりょく",k:"魅力",r:"miryoku",m:"매력"},
    {h:"じっちちょうさ",k:"実地調査",r:"jicchi chousa",m:"현장 조사"},
    // 동사
    {h:"なめる",r:"nameru",m:"맛보다/핥다"},
    {h:"むす",k:"蒸す",r:"musu",m:"찌다"},
    {h:"あえる",r:"aeru",m:"무치다 (요리)"},
    {h:"つれてくる",k:"連れてくる",r:"tsuretekuru",m:"데려오다"},
    {h:"ふれあう",k:"触れ合う",r:"fureau",m:"스치다/닿다"},
    // 형용사·부사
    {h:"にがい",k:"苦い",r:"nigai",m:"쓰다"},
    {h:"めずらしい",k:"珍しい",r:"mezurashii",m:"드물다/진귀하다"},
    {h:"ビチョビチョ",r:"bichobicho",m:"촉촉한/축축한"},
  ];
WORD_DATA_MIKMAT[8] = { title: "4화 표현 (최고의 술안주, 오마카세 야키토리)", words: [
    {h:"お出しさせていただいてよろしいですか",r:"odashi sasete itadaite yoroshii desu ka",m:"(요리를) 내드려도 될까요?"},
    {h:"焼き鳥はお酒の…",r:"yakitori wa osake no...",m:"야키토리는 술의… (술안주)"},
    {h:"ビールまず飲んで",r:"biiru mazu nonde",m:"먼저 맥주부터 마셔"},
    {h:"黒龍なめてもいい？",r:"kokuryu namete mo ii?",m:"코쿠류 맛봐도 돼?"},
    {h:"蒸し鶏と九条ネギの酢味噌あえ",r:"mushidori to kujou negi no sumiso ae",m:"찜닭과 구조파의 초된장 무침"},
    {h:"里芋の煮物になっております",r:"satoimo no nimono ni natte orimasu",m:"토란 조림입니다"},
    {h:"肉のうまみが凝縮してくるので",r:"niku no umami ga gyoushuku shite kuru node",m:"고기 감칠맛이 응축되니까"},
    {h:"両親を連れてきたくなる味",r:"ryoushin wo tsurete kitaku naru aji",m:"부모님을 모시고 오고 싶은 맛"},
    {h:"親孝行したじゃない",r:"oyakoukou shita ja nai",m:"효도했잖아"},
    {h:"お酒を飲むべき店です",r:"osake wo nomu beki mise desu",m:"술을 마셔야 할 가게입니다"},
    {h:"飲みながら食べるとよりおいしい",r:"nominagara taberu to yori oishii",m:"마시면서 먹으면 더 맛있다"},
    {h:"リセットされるの完全に",r:"risetto sareru no kanzen ni",m:"완전히 리셋돼"},
    {h:"卵黄を卵管から外す",r:"ran'ou wo rankan kara hazusu",m:"난황을 난관에서 떼어내다"},
    {h:"串持って食べるの",r:"kushi motte taberu no",m:"꼬치 잡고 먹는 거야"},
    {h:"手が触れ合ったりするの",r:"te ga fureatari suru no",m:"손이 스치기도 하고"},
    {h:"10羽から1串取れるか取れないか",r:"juu wa kara hito kushi toreru ka torenai ka",m:"10마리에서 꼬치 1개 나올까 말까"},
    {h:"非常に希少な部位になっております",r:"hijou ni kishou na bui ni natte orimasu",m:"매우 희귀한 부위입니다"},
    {h:"大人の魅力です",r:"otona no miryoku desu",m:"어른의 매력이에요"},
    {h:"苦みもあって",r:"nigami mo atte",m:"쓴맛도 있어서"},
    {h:"酒飲みは大好きな味",r:"sakenomi wa daisuki na aji",m:"술꾼이 좋아하는 맛"},
    {h:"こんな店は珍しい",r:"konna mise wa mezurashii",m:"이런 가게는 드물다"},
  ];
