// 미친맛집 시즌1 - 5화
WORD_DATA_MIKMAT[9] = { title: "5화 단어 (해질녘 후지산과 환상적인 푸딩)", words: [
    // 명사
    {h:"デート",r:"deeto",m:"데이트"},
    {h:"せいそう",k:"正装",r:"seisou",m:"정장/격식 차림"},
    {h:"ふじさん",k:"富士山",r:"fujisan",m:"후지산"},
    {h:"プリン",r:"purin",m:"푸딩"},
    {h:"カスタード",r:"kasutaado",m:"커스터드"},
    {h:"ほっかいどう",k:"北海道",r:"hokkaidou",m:"홋카이도 (지명)"},
    {h:"もりあわせ",k:"盛り合わせ",r:"moriawase",m:"모둠"},
    {h:"おまかせ",k:"お任せ",r:"omakase",m:"오마카세/맡김"},
    {h:"ていばん",k:"定番",r:"teiban",m:"정석/기본"},
    {h:"カラメル",r:"karameru",m:"카라멜"},
    {h:"コンビニ",r:"konbini",m:"편의점"},
    {h:"ぎゅうにゅう",k:"牛乳",r:"gyuunyuu",m:"우유"},
    {h:"えいよう",k:"栄養",r:"eiyou",m:"영양"},
    {h:"れんあい",k:"恋愛",r:"ren'ai",m:"연애"},
    {h:"えいが",k:"映画",r:"eiga",m:"영화"},
    {h:"プレッシャー",r:"puresshaa",m:"부담/압박감"},
    {h:"どうせい",k:"同棲",r:"dousei",m:"동거"},
    {h:"つり",k:"釣り",r:"tsuri",m:"낚시"},
    {h:"ゆうやけ",k:"夕焼け",r:"yuuyake",m:"노을/석양"},
    {h:"もちごめ",k:"もち米",r:"mochigome",m:"찹쌀"},
    {h:"ドーナツ",r:"doonatsu",m:"도넛"},
    {h:"いちば",k:"市場",r:"ichiba",m:"시장"},
    {h:"かし",k:"歌詞",r:"kashi",m:"가사"},
    {h:"かおり",k:"香り",r:"kaori",m:"향기"},
    {h:"デザート",r:"dezaato",m:"디저트"},
    {h:"あきや",k:"秋谷",r:"akiya",m:"아키야 (지명)"},
    {h:"できたて",k:"出来立て",r:"dekitate",m:"갓 만든/방금 만든"},
    // 동사
    {h:"みえる",k:"見える",r:"mieru",m:"보이다"},
    {h:"くれる",k:"暮れる",r:"kureru",m:"(해가) 지다"},
    {h:"ほめる",k:"褒める",r:"homeru",m:"칭찬하다"},
    {h:"こがす",k:"焦がす",r:"kogasu",m:"태우다/그을리다"},
    {h:"しゃべる",r:"shaberu",m:"수다 떨다/이야기하다"},
    // 형용사·부사
    {h:"じょうひん",k:"上品",r:"jouhin",m:"고상한/품위 있는"},
    {h:"こうきゅう",k:"高級",r:"koukyuu",m:"고급"},
    {h:"すばらしい",r:"subarashii",m:"훌륭하다/멋지다"},
    {h:"ワクワク",r:"wakuwaku",m:"두근두근/설레다"},
    {h:"おしゃれ",r:"oshare",m:"세련되다/멋지다"},
  ];
WORD_DATA_MIKMAT[10] = { title: "5화 표현 (해질녘 후지산과 환상적인 푸딩)", words: [
    {h:"デートみたいなもんですよ",r:"deeto mitai na mon desu yo",m:"데이트 같은 거잖아요"},
    {h:"正装して",r:"seisou shite",m:"정장 입고"},
    {h:"入った瞬間",r:"haitta shunkan",m:"들어간 순간"},
    {h:"昔よく釣りに来てたんですよ",r:"mukashi yoku tsuri ni kitetandesu yo",m:"옛날에 낚시하러 자주 왔었어요"},
    {h:"見えそうで見えなさそうで",r:"miesou de mienasasou de",m:"보일 듯 안 보일 듯해서"},
    {h:"転換が速い",r:"tenkan ga hayai",m:"전환이 빠르다"},
    {h:"この時間やってない",r:"kono jikan yattenai",m:"이 시간에 안 해요"},
    {h:"カスタードプリンを食べられるか",r:"kasutaado purin wo taberareru ka",m:"커스터드 푸딩을 먹거나"},
    {h:"お任せ2種にします",r:"omakase nishu ni shimasu",m:"오마카세 2종으로 할게요"},
    {h:"定番っていうのも",r:"teiban tte iu no mo",m:"정석이라는 것도"},
    {h:"映画のためですか",r:"eiga no tame desu ka",m:"영화 때문인가요?"},
    {h:"プレッシャーがあったんだと感じました",r:"puresshaa ga attanda to kanjimashita",m:"부담이 있었다고 느꼈어요"},
    {h:"顔が知られてる人間の人生って",r:"kao ga shirareteru ningen no jinsei tte",m:"얼굴이 알려진 사람의 인생이란"},
    {h:"一緒に住み始めたから",r:"issho ni sumi hajimeta kara",m:"같이 살기 시작해서"},
    {h:"ディープな話はちょっと",r:"diipu na hanashi wa chotto",m:"깊은 얘기는 좀…"},
    {h:"あれにしておけばよかった",r:"are ni shite okeba yokatta",m:"그걸로 할 걸 그랬어"},
    {h:"めちゃくちゃおいしいです",r:"mechakucha oishii desu",m:"엄청 맛있어요"},
    {h:"カラメルの香りがいいし",r:"karameru no kaori ga ii shi",m:"카라멜 향이 좋고"},
    {h:"ちょっと焦がしてる味が",r:"chotto kogashiteru aji ga",m:"살짝 태운 맛이"},
    {h:"栄養たっぷりですか",r:"eiyou tappuri desu ka",m:"영양이 풍부해요?"},
    {h:"体によさそうだよね",r:"karada ni yosa sou da yo ne",m:"몸에 좋을 것 같지?"},
    {h:"一富士 二鷹 三茄子",r:"ichi fuji ni taka san nasubi",m:"첫째 후지산, 둘째 매, 셋째 가지 (초몽 격언)"},
    {h:"夕焼け一緒に見て",r:"yuuyake issho ni mite",m:"노을을 함께 보며"},
    {h:"ワクワクするかも",r:"wakuwaku suru kamo",m:"설렐지도 몰라"},
    {h:"やっと褒められた",r:"yatto homerareta",m:"겨우 칭찬받았다"},
    {h:"おしゃれな響きがね",r:"oshare na hibiki ga ne",m:"세련된 어감이"},
    {h:"出来立てがおいしいんです",r:"dekitate ga oishiindesu",m:"갓 만든 게 맛있어요"},
  ];
