// 미친맛집 시즌1 - 6화
WORD_DATA_MIKMAT[11] = { title: "6화 단어 (40년 단골 맛집, 노포 중식당)", words: [
    // 명사
    {h:"せき",k:"席",r:"seki",m:"좌석/석"},
    {h:"まち",k:"町",r:"machi",m:"거리/동네"},
    {h:"しもきたざわ",k:"下北沢",r:"shimokitazawa",m:"시모키타자와 (지명)"},
    {h:"ちか",k:"地下",r:"chika",m:"지하"},
    {h:"でまえ",k:"出前",r:"demae",m:"배달 (음식)"},
    {h:"ラーメン",r:"raamen",m:"라멘"},
    {h:"チャーハン",r:"chaahan",m:"볶음밥"},
    {h:"ぎょうざ",k:"餃子",r:"gyouza",m:"만두/교자"},
    {h:"やきぎょうざ",k:"焼餃子",r:"yakigyouza",m:"군만두"},
    {h:"まちちゅうか",k:"町中華",r:"machichuuka",m:"동네 중화요리집"},
    {h:"じきゅう",k:"時給",r:"jikyuu",m:"시급"},
    {h:"にっきゅう",k:"日給",r:"nikkyuu",m:"일급"},
    {h:"マスター",r:"masutaa",m:"마스터/사장"},
    {h:"しゅじん",k:"主人",r:"shujin",m:"남편/주인"},
    {h:"えどっこ",k:"江戸っ子",r:"edokko",m:"에돗코 (도쿄 토박이)"},
    {h:"スープ",r:"suupu",m:"국물/수프"},
    {h:"チャーシュー",r:"chaashuu",m:"차슈"},
    {h:"ふとめん",k:"太麺",r:"futomen",m:"굵은 면"},
    {h:"あぶら",k:"油",r:"abura",m:"기름"},
    {h:"おんど",k:"温度",r:"ondo",m:"온도"},
    {h:"ぶたい",k:"舞台",r:"butai",m:"무대"},
    {h:"やくしゃ",k:"役者",r:"yakusha",m:"배우"},
    {h:"えいがかんとく",k:"映画監督",r:"eiga kantoku",m:"영화 감독"},
    {h:"ゆめ",k:"夢",r:"yume",m:"꿈"},
    {h:"うちあげ",k:"打ち上げ",r:"uchiage",m:"뒤풀이"},
    {h:"せっきゃく",k:"接客",r:"sekkyaku",m:"접객/서빙"},
    {h:"レシピ",r:"reshipi",m:"레시피"},
    {h:"コップ",r:"koppu",m:"컵/잔"},
    // 동사
    {h:"いためる",k:"炒める",r:"itameru",m:"볶다"},
    {h:"やめる",k:"辞める",r:"yameru",m:"그만두다"},
    {h:"かなう",k:"叶う",r:"kanau",m:"(꿈이) 이루어지다"},
    {h:"はこぶ",k:"運ぶ",r:"hakobu",m:"나르다/옮기다"},
    {h:"たく",k:"炊く",r:"taku",m:"(밥을) 짓다"},
    {h:"ひたす",k:"浸す",r:"hitasu",m:"담그다/적시다"},
    // 형용사·부사
    {h:"あかい",k:"赤い",r:"akai",m:"빨갛다"},
    {h:"せっかち",r:"sekkachi",m:"성급하다/급한 성격"},
    {h:"ぜっぴん",k:"絶品",r:"zeppin",m:"절품/최고의 맛"},
    {h:"のうこう",k:"濃厚",r:"noukou",m:"진한/농후한"},
    {h:"ぎりぎり",r:"girigiri",m:"아슬아슬/겨우"},
  ];
WORD_DATA_MIKMAT[12] = { title: "6화 표현 (40년 단골 맛집, 노포 중식당)", words: [
    {h:"ごちゃごちゃしてて",r:"gochagocha shitete",m:"어수선하고/복잡하고"},
    {h:"出前持ってってたし",r:"demae mottetteta shi",m:"배달도 가져다줬고"},
    {h:"40年変わらない場所です",r:"yonjuunen kawaranai basho desu",m:"40년 변하지 않는 곳입니다"},
    {h:"適当にちゃっと炒めたりもできるし",r:"tekitou ni chatto itametari mo dekiru shi",m:"적당히 후딱 볶을 수도 있고"},
    {h:"5時間働いて3000円",r:"gojikan hataraite sanzen en",m:"5시간 일하고 3000엔"},
    {h:"赤いチャーハンで有名なんですけど",r:"akai chaahan de yuumei nandesu kedo",m:"빨간 볶음밥으로 유명한데요"},
    {h:"町中華はチャーハンでしょう",r:"machichuuka wa chaahan deshou",m:"동네 중화는 볶음밥이죠?"},
    {h:"40年前と何も変わらない",r:"yonjuunen mae to nanimo kawaranai",m:"40년 전과 아무것도 변하지 않았다"},
    {h:"レシピを全部知っている",r:"reshipi wo zenbu shitte iru",m:"레시피를 전부 알고 있다"},
    {h:"赤い味はしないですよ",r:"akai aji wa shinai desu yo",m:"빨간 맛은 안 나요"},
    {h:"目つぶると赤いの関係なくて",r:"me tsuburu to akai no kankei nakute",m:"눈 감으면 빨간 건 상관없고"},
    {h:"スープも飲んだほうがいいですよね",r:"suupu mo nonda hou ga ii desu yo ne",m:"국물도 마시는 게 좋죠"},
    {h:"体にしみる感じ",r:"karada ni shimiru kanji",m:"몸에 스며드는 느낌"},
    {h:"僕も太麺だめなの",r:"boku mo futomen dame na no",m:"나도 굵은 면은 안 돼"},
    {h:"このラーメン好きです",r:"kono raamen suki desu",m:"이 라멘 좋아해요"},
    {h:"ラーメンスープにチャーハンを浸す",r:"raamen suupu ni chaahan wo hitasu",m:"라멘 국물에 볶음밥을 적시다"},
    {h:"スープで追っかければいいですよ",r:"suupu de oikkakereba ii desu yo",m:"국물로 쫓아가면 돼요"},
    {h:"油のうまみが温度が上がるでしょ",r:"abura no umami ga ondo ga agaru desho",m:"기름의 감칠맛이 온도 오르면"},
    {h:"花開くんだ",r:"hana hirakunda",m:"활짝 피어나는 거야"},
    {h:"サーブするからみんな食べろって",r:"saabu suru kara minna tabero tte",m:"서빙할 테니까 다 먹으라고"},
    {h:"夢がかなった",r:"yume ga kanatta",m:"꿈이 이루어졌다"},
    {h:"映画監督はやめますって言ってから",r:"eiga kantoku wa yamemasu tte itte kara",m:"영화 감독은 그만두겠다고 한 후"},
    {h:"時給600円でございます",r:"jikyuu roppyaku en de gozaimasu",m:"시급 600엔이옵니다"},
    {h:"自分が何を食べたいか考えといてください",r:"jibun ga nani wo tabetai ka kangaetoite kudasai",m:"자기가 뭘 먹고 싶은지 생각해 두세요"},
    {h:"日本人は絶対に好き",r:"nihonjin wa zettai ni suki",m:"일본 사람은 무조건 좋아해"},
    {h:"ミッチョッタですよねこれ",r:"micchotta desu yo ne kore",m:"미쳤다죠 이거"},
  ];
