// 미친맛집 시즌1 - 7화
WORD_DATA_MIKMAT[13] = { title: "7화 단어 (30년 노포의 품격, 부일숯불갈비)", words: [
    // 명사
    {h:"ガイドブック",r:"gaidobukku",m:"가이드북"},
    {h:"えと",k:"干支",r:"eto",m:"띠/간지"},
    {h:"うさぎ",k:"兎",r:"usagi",m:"토끼"},
    {h:"うどし",k:"卯年",r:"udoshi",m:"토끼띠해"},
    {h:"りょうり",k:"料理",r:"ryouri",m:"요리"},
    {h:"でんとう",k:"伝統",r:"dentou",m:"전통"},
    {h:"れきし",k:"歴史",r:"rekishi",m:"역사"},
    {h:"すみび",k:"炭火",r:"sumibi",m:"숯불"},
    {h:"しゅざい",k:"取材",r:"shuzai",m:"취재"},
    {h:"きょか",k:"許可",r:"kyoka",m:"허가"},
    {h:"ちゅうもん",k:"注文",r:"chuumon",m:"주문"},
    {h:"やさい",k:"野菜",r:"yasai",m:"야채/채소"},
    {h:"だいこん",k:"大根",r:"daikon",m:"무"},
    {h:"なふだ",k:"名札",r:"nafuda",m:"명찰"},
    {h:"バッジ",r:"bajji",m:"배지"},
    {h:"おまもり",k:"お守り",r:"omamori",m:"부적"},
    {h:"チャイム",r:"chaimu",m:"벨/차임"},
    {h:"じょうれん",k:"常連",r:"jouren",m:"단골"},
    {h:"たまねぎ",k:"玉ねぎ",r:"tamanegi",m:"양파"},
    {h:"こんぶ",k:"昆布",r:"konbu",m:"다시마"},
    {h:"わかめ",r:"wakame",m:"미역"},
    {h:"のり",r:"nori",m:"김"},
    {h:"かいそう",k:"海藻",r:"kaisou",m:"해초"},
    {h:"つうやく",k:"通訳",r:"tsuuyaku",m:"통역"},
    {h:"しょうちゅう",k:"焼酎",r:"shouchuu",m:"소주"},
    {h:"くちなおし",k:"口直し",r:"kuchinaoshi",m:"입가심"},
    {h:"ねんき",k:"年季",r:"nenki",m:"연륜/경력"},
    {h:"ほうげん",k:"方言",r:"hougen",m:"방언"},
    {h:"けいたい",k:"携帯",r:"keitai",m:"휴대전화"},
    {h:"にんまえ",k:"人前",r:"ninmae",m:"~인분"},
    {h:"サービス",r:"saabisu",m:"서비스/무료 제공"},
    // 동사
    {h:"たべあるく",k:"食べ歩く",r:"tabearuku",m:"먹으러 다니다"},
    {h:"しみでる",k:"染み出る",r:"shimideru",m:"배어 나오다"},
    {h:"えんりょする",k:"遠慮する",r:"enryo suru",m:"사양하다"},
    {h:"きまる",k:"決まる",r:"kimaru",m:"정해지다"},
    // 형용사·부사
    {h:"こうばしい",k:"香ばしい",r:"koubashii",m:"고소하다"},
    {h:"しんせん",k:"新鮮",r:"shinsen",m:"신선하다"},
    {h:"あつい",k:"厚い",r:"atsui",m:"두껍다"},
    {h:"やわらかい",k:"柔らかい",r:"yawarakai",m:"부드럽다"},
    {h:"めちゃくちゃ",r:"mechakucha",m:"엄청/무지"},
    {h:"いがいと",k:"意外と",r:"igai to",m:"의외로"},
    {h:"かってに",k:"勝手に",r:"katte ni",m:"마음대로/멋대로"},
    {h:"せっかち",r:"sekkachi",m:"성급하다"},
  ];
WORD_DATA_MIKMAT[14] = { title: "7화 표현 (30년 노포의 품격, 부일숯불갈비)", words: [
    {h:"ぜひ先に召し上がってください",r:"zehi saki ni meshiagatte kudasai",m:"꼭 먼저 드세요"},
    {h:"任せてください",r:"makasete kudasai",m:"맡겨주세요"},
    {h:"ご注文はお決まりですか？",r:"gochuumon wa okimari desu ka?",m:"주문은 정하셨나요?"},
    {h:"テジカルビを２人前",r:"teji karubi wo nininmae",m:"돼지갈비 2인분"},
    {h:"追加 無料",r:"tsuika muryou",m:"추가 무료"},
    {h:"足りないものは全部持ってくればいい",r:"tarinai mono wa zenbu mottekureba ii",m:"부족한 건 다 가져오면 돼"},
    {h:"めちゃくちゃ安いじゃん",r:"mechakucha yasui jan",m:"엄청 싸잖아"},
    {h:"食べたことないですか？",r:"tabeta koto nai desu ka?",m:"먹어본 적 없어요?"},
    {h:"取材の許可をありがとうございます",r:"shuzai no kyoka wo arigatou gozaimasu",m:"취재 허가 감사합니다"},
    {h:"炭火が登場",r:"sumibi ga toujou",m:"숯불 등장"},
    {h:"肉が焦げないし",r:"niku ga kogenai shi",m:"고기가 안 타니까"},
    {h:"大根がクッションなの？",r:"daikon ga kusshon na no?",m:"무가 쿠션 역할이야?"},
    {h:"おいしいね(マシンネ)",r:"oishii ne (masinne)",m:"맛있네"},
    {h:"年季が入ってるもの",r:"nenki ga haitteru mono",m:"연륜이 있는 거야"},
    {h:"白いご飯と一緒に食べてみて",r:"shiroi gohan to issho ni tabete mite",m:"흰밥이랑 같이 먹어봐"},
    {h:"子供にはライス頼んであげて",r:"kodomo ni wa raisu tanonde agete",m:"아이에게는 밥 시켜줘"},
    {h:"このサムの文化って結構長いって",r:"kono samu no bunka tte kekkou nagai tte",m:"이 쌈 문화는 꽤 오래됐대"},
    {h:"まだサムの間柄じゃない",r:"mada samu no aidagara ja nai",m:"아직 쌈 사이는 아니야"},
    {h:"これで口直しをして",r:"kore de kuchinaoshi wo shite",m:"이걸로 입가심 하고"},
    {h:"味付けが強いんで",r:"ajitsuke ga tsuyoin de",m:"양념이 진해서"},
    {h:"最後までおいしいね",r:"saigo made oishii ne",m:"끝까지 맛있네"},
    {h:"意外と皮って厚いんだね",r:"igai to kawa tte atsuin da ne",m:"의외로 껍질이 두껍네"},
    {h:"お疲れさまでした",r:"otsukaresama deshita",m:"수고하셨습니다"},
    {h:"染み出てくるような店のほうが",r:"shimidete kuru you na mise no hou ga",m:"(맛이) 배어 나오는 가게가 더"},
  ];
