// 미친맛집 시즌1 - 8화
WORD_DATA_MIKMAT[15] = { title: "8화 단어 (중독된 사랑, 평양냉면)", words: [
    // 명사
    {h:"れいめん",k:"冷麺",r:"reimen",m:"냉면"},
    {h:"へいじょう",k:"平壌",r:"heijou",m:"평양"},
    {h:"マンドゥ",r:"mandu",m:"만두 (한국식)"},
    {h:"むしギョーザ",k:"蒸し餃子",r:"mushi gyouza",m:"찐만두"},
    {h:"スープ",r:"suupu",m:"국물/스프"},
    {h:"だし",r:"dashi",m:"육수"},
    {h:"ぐんたい",k:"軍隊",r:"guntai",m:"군대"},
    {h:"おす",k:"お酢",r:"osu",m:"식초"},
    {h:"シメ",r:"shime",m:"마무리 (식사)"},
    {h:"ふうみ",k:"風味",r:"fuumi",m:"풍미"},
    {h:"すがらし",k:"酢がらし",r:"sugarashi",m:"초겨자"},
    {h:"ごまあぶら",k:"ごま油",r:"goma abura",m:"참기름"},
    {h:"かえだま",k:"替え玉",r:"kaedama",m:"면 추가/사리"},
    {h:"しょうかこうそ",k:"消化酵素",r:"shouka kouso",m:"소화효소"},
    {h:"でんぷん",r:"denpun",m:"전분"},
    {h:"ジャガイモ",r:"jagaimo",m:"감자"},
    {h:"しょしんしゃ",k:"初心者",r:"shoshinsha",m:"초보자"},
    {h:"しょたいけん",k:"初体験",r:"shotaiken",m:"첫 경험"},
    {h:"ゆでたまご",k:"ゆで卵",r:"yudetamago",m:"삶은 달걀"},
    {h:"だんりょく",k:"弾力",r:"danryoku",m:"탄력"},
    {h:"あつりょく",k:"圧力",r:"atsuryoku",m:"압력"},
    {h:"きおく",k:"記憶",r:"kioku",m:"기억"},
    {h:"よだれ",r:"yodare",m:"침/군침"},
    {h:"もちぬし",k:"持ち主",r:"mochinushi",m:"주인"},
    {h:"いちみ",k:"一味",r:"ichimi",m:"일미/고춧가루"},
    {h:"めんや",k:"麺屋",r:"men'ya",m:"면옥/국수집"},
    {h:"ヤンニョム",r:"yannyomu",m:"양념 (한국식)"},
    {h:"まなつ",k:"真夏",r:"manatsu",m:"한여름"},
    {h:"にゅうもん",k:"入門",r:"nyuumon",m:"입문"},
    {h:"みため",k:"見た目",r:"mitame",m:"겉모양/생김새"},
    {h:"デザート",r:"dezaato",m:"디저트"},
    // 동사
    {h:"かよう",k:"通う",r:"kayou",m:"다니다"},
    {h:"のびる",k:"伸びる",r:"nobiru",m:"(면이) 불다/늘어나다"},
    {h:"ほぐす",r:"hogusu",m:"풀다/비비다"},
    {h:"つぶす",k:"潰す",r:"tsubusu",m:"으깨다"},
    {h:"まぜる",k:"混ぜる",r:"mazeru",m:"섞다"},
    {h:"うけいれる",k:"受け入れる",r:"ukeireru",m:"받아들이다"},
    // 형용사·부사
    {h:"つめたい",k:"冷たい",r:"tsumetai",m:"차갑다"},
    {h:"あっさり",r:"assari",m:"담백하다"},
    {h:"おくぶかい",k:"奥深い",r:"okufukai",m:"깊다/심오하다"},
    {h:"してき",k:"詩的",r:"shiteki",m:"시적인"},
    {h:"じょじょに",k:"徐々に",r:"jojo ni",m:"서서히"},
  ];
WORD_DATA_MIKMAT[16] = { title: "8화 표현 (중독된 사랑, 평양냉면)", words: [
    {h:"寂しいこと言わないで",r:"sabishii koto iwanaide",m:"쓸쓸한 말 하지 마"},
    {h:"付き合ってあげるよ",r:"tsukiatte ageru yo",m:"같이 가줄게"},
    {h:"入ってみますか",r:"haitte mimasu ka",m:"들어가 볼까요?"},
    {h:"食べて話してから注文しましょう",r:"tabete hanashite kara chuumon shimashou",m:"먹어보고 나서 주문하자"},
    {h:"よだれが止まらない",r:"yodare ga tomaranai",m:"침이 안 멈춰"},
    {h:"冷麺に集中しないと伸びるし",r:"reimen ni shuuchuu shinai to nobiru shi",m:"냉면에 집중 안 하면 불잖아"},
    {h:"麺をちゃんとほぐして",r:"men wo chanto hogushite",m:"면을 잘 풀어서"},
    {h:"与えられた味を受け入れるんじゃなく",r:"ataerareta aji wo ukeireru n ja naku",m:"주어진 맛을 받아들이는 게 아니라"},
    {h:"死ぬまで食べたい",r:"shinu made tabetai",m:"죽을 때까지 먹고 싶다"},
    {h:"スープが全部汚れちゃうんで",r:"suupu ga zenbu yogorechau n de",m:"국물이 다 탁해지니까"},
    {h:"巻きたくなっちゃう",r:"makitaku nacchau",m:"쌈 싸고 싶어진다"},
    {h:"具なしで麺大盛り",r:"gu nashi de men oomori",m:"건더기 없이 면 곱빼기"},
    {h:"初体験が大事",r:"shotaiken ga daiji",m:"첫 경험이 중요해"},
    {h:"ここで入門したら",r:"koko de nyuumon shitara",m:"여기서 입문하면"},
    {h:"東京じゃ食えないね",r:"toukyou ja kuenai ne",m:"도쿄에서는 못 먹어"},
    {h:"消化酵素がブワッと出てきて",r:"shouka kouso ga buwatto detekite",m:"소화효소가 확 나와서"},
    {h:"初心者はこのピビンをよく頼むんです",r:"shoshinsha wa kono pibin wo yoku tanomun desu",m:"초보자는 이 비빔을 자주 시켜요"},
    {h:"肉のだしとトンチミのスープを混ぜて",r:"niku no dashi to tonchimi no suupu wo mazete",m:"고기 육수와 동치미 국물을 섞어서"},
    {h:"見た目がまた全然違うなあ",r:"mitame ga mata zenzen chigau naa",m:"생긴 게 또 완전 다르네"},
    {h:"圧力をかけて長い間置いておくと",r:"atsuryoku wo kakete nagai aida oite oku to",m:"압력을 가해서 오래 놔두면"},
    {h:"うまみも味ももっと増える",r:"umami mo aji mo motto fueru",m:"감칠맛도 맛도 더 늘어나"},
    {h:"知らないとこドライブしながら",r:"shiranai toko doraibu shinagara",m:"모르는 곳 드라이브하면서"},
    {h:"焼肉屋さんで最後にシメで",r:"yakinikuya san de saigo ni shime de",m:"야키니쿠집에서 마지막에 마무리로"},
    {h:"真夏にふさわしいんじゃない？",r:"manatsu ni fusawashiin ja nai?",m:"한여름에 어울리지 않아?"},
  ];
