// 미친맛집 시즌1 - 9화
WORD_DATA_MIKMAT[17] = { title: "9화 단어 (단맛 충전소, 약수시장 디저트 투어)", words: [
    // 명사
    {h:"やくすいしじょう",k:"薬水市場",r:"yakusui shijou",m:"약수시장 (지명)"},
    {h:"かんこうきゃく",k:"観光客",r:"kankoukyaku",m:"관광객"},
    {h:"できたて",k:"出来たて",r:"dekitate",m:"갓 만든 것"},
    {h:"じょうおん",k:"常温",r:"jouon",m:"상온/실온"},
    {h:"れいぞうこ",k:"冷蔵庫",r:"reizouko",m:"냉장고"},
    {h:"ドーナツ",r:"doonatsu",m:"도넛"},
    {h:"しゅるい",k:"種類",r:"shurui",m:"종류"},
    {h:"もちごめ",k:"もち米",r:"mochigome",m:"찹쌀"},
    {h:"プレーン",r:"pureen",m:"플레인/기본 맛"},
    {h:"くだものや",k:"果物屋",r:"kudamonoya",m:"과일가게"},
    {h:"さかなや",k:"魚屋",r:"sakanaya",m:"생선가게"},
    {h:"パン",r:"pan",m:"빵"},
    {h:"ポテト",r:"poteto",m:"감자/포테이토"},
    {h:"バター",r:"bataa",m:"버터"},
    {h:"おかし",k:"お菓子",r:"okashi",m:"과자"},
    {h:"あまさ",k:"甘さ",r:"amasa",m:"단맛/달기"},
    {h:"こうばしさ",k:"香ばしさ",r:"koubashisa",m:"고소함"},
    {h:"クリーム",r:"kuriimu",m:"크림"},
    {h:"しゃしん",k:"写真",r:"shashin",m:"사진"},
    {h:"けしょうひん",k:"化粧品",r:"keshouhin",m:"화장품"},
    {h:"ふくぎょう",k:"副業",r:"fukugyou",m:"부업"},
    {h:"じゅんい",k:"順位",r:"jun'i",m:"순위/등수"},
    {h:"かこけい",k:"過去形",r:"kakokei",m:"과거형"},
    {h:"えいぞう",k:"映像",r:"eizou",m:"영상"},
    {h:"サービス",r:"saabisu",m:"서비스/무료 제공"},
    {h:"へんかきゅう",k:"変化球",r:"henkakyuu",m:"변화구"},
    {h:"オーディエンス",r:"oodiensu",m:"청중/관객"},
    // 동사
    {h:"あじみする",k:"味見する",r:"ajimi suru",m:"맛보다/시식하다"},
    {h:"じゅくせいさせる",k:"熟成させる",r:"jukusei saseru",m:"숙성시키다"},
    {h:"うれる",k:"売れる",r:"ureru",m:"팔리다"},
    {h:"けいさんする",k:"計算する",r:"keisan suru",m:"계산하다"},
    {h:"りかいする",k:"理解する",r:"rikai suru",m:"이해하다"},
    {h:"つらぬく",k:"貫く",r:"tsuranuku",m:"관철하다/밀고 나가다"},
    {h:"まよう",k:"迷う",r:"mayou",m:"망설이다/헤매다"},
    {h:"きめる",k:"決める",r:"kimeru",m:"결정하다"},
    {h:"ちぎる",r:"chigiru",m:"뜯다/찢다"},
    {h:"こまる",k:"困る",r:"komaru",m:"곤란하다/난처하다"},
    // 형용사·부사
    {h:"げきやすい",k:"激安い",r:"gekiyasui",m:"엄청 싸다"},
    {h:"かるい",k:"軽い",r:"karui",m:"가볍다"},
    {h:"めちゃくちゃ",r:"mechakucha",m:"엄청/매우 (구어)"},
    {h:"みじかい",k:"短い",r:"mijikai",m:"짧다"},
  ];
WORD_DATA_MIKMAT[18] = { title: "9화 표현 (단맛 충전소, 약수시장 디저트 투어)", words: [
    {h:"出来たてを味見しますか？",r:"dekitate wo ajimi shimasu ka?",m:"갓 만든 걸 맛보시겠어요?"},
    {h:"気をつけてください",r:"ki wo tsukete kudasai",m:"조심하세요"},
    {h:"常温で３日間ほど",r:"jouon de mikkakan hodo",m:"상온에서 3일 정도"},
    {h:"冷蔵庫で１週間ほどです",r:"reizouko de isshuukan hodo desu",m:"냉장고에서 1주일 정도입니다"},
    {h:"またお越しください",r:"mata okoshi kudasai",m:"다음에 또 와주세요"},
    {h:"お世話さま",r:"osewa sama",m:"수고하세요"},
    {h:"種類が結構ありまして",r:"shurui ga kekkou arimashite",m:"종류가 꽤 있어서"},
    {h:"結構軽いんだね",r:"kekkou karuin da ne",m:"꽤 가벼운데"},
    {h:"空ですよ 中は空",r:"kara desu yo naka wa kara",m:"비어있어요, 안은 비어있어"},
    {h:"熟成させてる？",r:"jukusei saseteru?",m:"숙성하는 거야?"},
    {h:"めちゃくちゃ好きだと思う",r:"mechakucha suki da to omou",m:"엄청 좋아할 것 같아"},
    {h:"５個で２００円",r:"goko de nihyaku en",m:"5개에 200엔"},
    {h:"写真撮っていいですか？",r:"shashin totte ii desu ka?",m:"사진 찍어도 되나요?"},
    {h:"過去形の適用完了",r:"kakokei no tekiyou kanryou",m:"과거형 적용 완료"},
    {h:"この短いスパンで",r:"kono mijikai supan de",m:"이 짧은 간격으로"},
    {h:"他の店に行くんですよ",r:"hoka no mise ni ikun desu yo",m:"다른 가게에 가는 거예요"},
    {h:"ここの果物屋も激安い",r:"koko no kudamonoya mo gekiyasui",m:"여기 과일가게도 엄청 싸"},
    {h:"具が日本みたいに",r:"gu ga nihon mitai ni",m:"속재료가 일본처럼"},
    {h:"ポテトたっぷり入ってる",r:"poteto tappuri haitteru",m:"감자가 듬뿍 들어있는"},
    {h:"思ったより甘さがないの",r:"omotta yori amasa ga nai no",m:"생각보다 달지 않아"},
    {h:"びっくりするぐらい甘くない",r:"bikkuri suru gurai amakunai",m:"깜짝 놀랄 만큼 안 달아"},
    {h:"クリームの香ばしさだけ",r:"kuriimu no koubashisa dake",m:"크림의 고소함만"},
    {h:"こんな息子さんいたら困りますよね",r:"konna musukosan itara komarimasu yo ne",m:"이런 아들이 있으면 곤란하죠"},
    {h:"白ご飯食べたくなるでしょう？",r:"shiro gohan tabetaku naru deshou?",m:"흰밥이 먹고 싶어지죠?"},
    {h:"理解できるようになった気がします",r:"rikai dekiru you ni natta ki ga shimasu",m:"이해할 수 있게 된 것 같아요"},
    {h:"迷ってると周りに迷惑かけちゃうんだよね",r:"mayotteru to mawari ni meiwaku kakechau n da yo ne",m:"망설이면 주위에 폐를 끼치게 돼"},
    {h:"自分が決めないと",r:"jibun ga kimenai to",m:"자기가 결정하지 않으면"},
  ];
