// 미친맛집 시즌1 - 10화
WORD_DATA_MIKMAT[19] = { title: "10화 단어 (바닷가 1열, 해산물 뷔페 수산시장)", words: [
    // 명사
    {h:"ふくおか",k:"福岡",r:"fukuoka",m:"후쿠오카 (지명)"},
    {h:"しものせき",k:"下関",r:"shimonoseki",m:"시모노세키 (지명)"},
    {h:"からといちば",k:"唐戸市場",r:"karato ichiba",m:"가라토 시장"},
    {h:"いちば",k:"市場",r:"ichiba",m:"시장"},
    {h:"ひこうき",k:"飛行機",r:"hikouki",m:"비행기"},
    {h:"れきし",k:"歴史",r:"rekishi",m:"역사"},
    {h:"フグ",r:"fugu",m:"복어"},
    {h:"ふぐさし",k:"フグ刺し",r:"fugusashi",m:"복어회"},
    {h:"みそしる",k:"味噌汁",r:"misoshiru",m:"된장국"},
    {h:"ズワイガニ",r:"zuwaigani",m:"대게"},
    {h:"カニクリームコロッケ",r:"kani kuriimu korokke",m:"게크림 크로켓"},
    {h:"まきずし",k:"巻きずし",r:"makizushi",m:"마키스시/김밥"},
    {h:"かわりだね",k:"変わり種",r:"kawaridane",m:"색다른 종류/변종"},
    {h:"ひかりもの",k:"光りもの",r:"hikarimono",m:"등푸른 생선 (스시)"},
    {h:"エンガワ",r:"engawa",m:"엔가와 (광어 지느러미살)"},
    {h:"ノドグロ",r:"nodoguro",m:"노도구로 (눈볼대)"},
    {h:"あぶり",r:"aburi",m:"아부리 (살짝 구운 것)"},
    {h:"タコ",r:"tako",m:"문어"},
    {h:"からあげ",k:"から揚げ",r:"karaage",m:"가라아게/튀김"},
    {h:"タラ",r:"tara",m:"대구 (생선)"},
    {h:"フライ",r:"furai",m:"프라이/튀김"},
    {h:"タルタルソース",r:"tarutaru soosu",m:"타르타르소스"},
    {h:"しるもの",k:"汁物",r:"shirumono",m:"국물요리"},
    {h:"ふつかよい",k:"二日酔い",r:"futsukayoi",m:"숙취"},
    {h:"かいきょう",k:"海峡",r:"kaikyou",m:"해협"},
    {h:"ネタ",r:"neta",m:"네타 (스시 토핑/재료)"},
    {h:"はいゆう",k:"俳優",r:"haiyuu",m:"배우"},
    {h:"いなか",k:"田舎",r:"inaka",m:"시골"},
    {h:"かいじょう",k:"開場",r:"kaijou",m:"개장"},
    {h:"こうこく",k:"広告",r:"koukoku",m:"광고"},
    {h:"カロリー",r:"karorii",m:"칼로리"},
    // 동사
    {h:"かう",k:"買う",r:"kau",m:"사다"},
    {h:"えらぶ",k:"選ぶ",r:"erabu",m:"고르다/선택하다"},
    {h:"はがす",k:"剥がす",r:"hagasu",m:"벗기다/떼다"},
    {h:"あぶる",r:"aburu",m:"살짝 굽다/그슬리다"},
    {h:"こぼれる",r:"koboreru",m:"흘리다/쏟아지다"},
    {h:"およぐ",k:"泳ぐ",r:"oyogu",m:"헤엄치다"},
    {h:"こむ",k:"混む",r:"komu",m:"붐비다/혼잡하다"},
    // 형용사·부사
    {h:"きれい",r:"kirei",m:"예쁘다/깨끗하다"},
    {h:"かたい",k:"硬い",r:"katai",m:"딱딱하다/단단하다"},
    {h:"ひつぜんてきに",k:"必然的に",r:"hitsuzen teki ni",m:"필연적으로"},
    {h:"ひっしに",k:"必死に",r:"hisshi ni",m:"필사적으로"},
  ];
WORD_DATA_MIKMAT[20] = { title: "10화 표현 (바닷가 1열, 해산물 뷔페 수산시장)", words: [
    {h:"韓国人結構来てるんだ",r:"kankokujin kekkou kiteru n da",m:"한국인이 꽤 오는구나"},
    {h:"飛行機でも１時間もかからないし",r:"hikouki demo ichijikan mo kakaranai shi",m:"비행기로도 1시간도 안 걸리고"},
    {h:"50年以上の歴史がある",r:"gojuu nen ijou no rekishi ga aru",m:"50년 이상의 역사가 있다"},
    {h:"ちょっと入ってみます？",r:"chotto haitte mimasu?",m:"좀 들어가 볼까요?"},
    {h:"好きなもん買ってきなさいって",r:"suki na mon katte kinasai tte",m:"좋아하는 거 사 오라고"},
    {h:"甘いもんばかりだったんで",r:"amai mon bakari dattan de",m:"단 것만이었으니까"},
    {h:"フグ刺しが当たるわけじゃないんだ",r:"fugusashi ga ataru wake ja nain da",m:"복어회에 당첨되는 건 아니구나"},
    {h:"大人２人で何やってるんだ",r:"otona futari de nani yatteru n da",m:"어른 둘이서 뭐 하는 거야"},
    {h:"９時半から始まりますって",r:"kuji han kara hajimarimasu tte",m:"9시 반부터 시작한대요"},
    {h:"何からいく？まず",r:"nani kara iku? mazu",m:"뭐부터 갈까? 우선"},
    {h:"二日酔いなんで",r:"futsukayoi nan de",m:"숙취라서"},
    {h:"酒臭いなと思ってたんだよ",r:"sakekusai na to omottetan da yo",m:"술 냄새 나더라 했어"},
    {h:"名前何ていうの？",r:"namae nan te iu no?",m:"이름이 뭐야?"},
    {h:"結構人気あった 昔はね",r:"kekkou ninki atta mukashi wa ne",m:"꽤 인기 있었어, 옛날에는"},
    {h:"覚えてないって絶対",r:"oboete nai tte zettai",m:"분명 기억 못 할 거야"},
    {h:"名前覚えた？",r:"namae oboeta?",m:"이름 기억했어?"},
    {h:"早く選びに行かないと",r:"hayaku erabi ni ikanai to",m:"빨리 고르러 가야 돼"},
    {h:"どうしてもカニクリームコロッケが食べたいんです",r:"doushitemo kani kuriimu korokke ga tabetain desu",m:"어쨌든 게크림 크로켓이 먹고 싶어요"},
    {h:"持てなくなってきたね",r:"motenaku natte kita ne",m:"들 수 없게 됐네"},
    {h:"これはほんとにいい景色ですね",r:"kore wa honto ni ii keshiki desu ne",m:"이건 정말 좋은 경치네요"},
    {h:"魚は必然的においしくなるんじゃないですか？",r:"sakana wa hitsuzen teki ni oishiku narun ja nai desu ka?",m:"생선은 필연적으로 맛있어지는 거 아니에요?"},
    {h:"必死に泳がないと",r:"hisshi ni oyoganai to",m:"필사적으로 헤엄쳐야"},
    {h:"ご飯の量が多いよね",r:"gohan no ryou ga ooi yo ne",m:"밥 양이 많지"},
    {h:"海峡見ながらおすし食べるという",r:"kaikyou minagara osushi taberu to iu",m:"해협 보면서 스시 먹는다는"},
    {h:"ちゃんとカニの香りもするし",r:"chanto kani no kaori mo suru shi",m:"제대로 게 향도 나고"},
    {h:"フィレオフィッシュみたいな感じ",r:"fireo fisshu mitai na kanji",m:"필레오피시 같은 느낌"},
    {h:"タルタル多めで",r:"tarutaru oome de",m:"타르타르 많이 주세요"},
    {h:"ネタをこう剥がして",r:"neta wo kou hagashite",m:"재료를 이렇게 벗겨서"},
    {h:"個人的な見解です",r:"kojin teki na kenkai desu",m:"개인적인 견해입니다"},
    {h:"止まんないね最高",r:"tomannai ne saikou",m:"멈출 수 없어, 최고"},
  ];
