// 미친맛집 시즌1 - 11화
WORD_DATA_MIKMAT[21] = { title: "11화 단어 (소년 마츠시게 소울푸드)", words: [
    // 명사
    {h:"まんじゅう",k:"饅頭",r:"manjuu",m:"만주"},
    {h:"ソウルフード",r:"souru fuudo",m:"소울 푸드"},
    {h:"なまり",r:"namari",m:"사투리"},
    {h:"じょうきょう",k:"上京",r:"joukyou",m:"상경 (도쿄로 올라감)"},
    {h:"さんろう",k:"３浪",r:"sanrou",m:"삼수 (3번 재수)"},
    {h:"すりみ",k:"すり身",r:"surimi",m:"갈은 생선살/어묵 반죽"},
    {h:"やおや",k:"八百屋",r:"yaoya",m:"채소 가게/청과물 가게"},
    {h:"リヤカー",r:"riyakaa",m:"리어카"},
    {h:"あんこ",r:"anko",m:"앙금/팥소"},
    {h:"しろあん",k:"白あん",r:"shiroan",m:"흰 앙금"},
    {h:"くろあん",k:"黒あん",r:"kuroan",m:"검은 앙금/팥 앙금"},
    {h:"ていばん",k:"定番",r:"teiban",m:"기본/정석"},
    {h:"ぜっぴん",k:"絶品",r:"zeppin",m:"절품/일품"},
    {h:"せいけい",k:"整形",r:"seikei",m:"성형"},
    {h:"りょう",k:"量",r:"ryou",m:"양/분량"},
    {h:"くいごたえ",k:"食い応え",r:"kuigotae",m:"먹음직함/든든함"},
    {h:"ごぼう",k:"牛蒡",r:"gobou",m:"우엉"},
    {h:"つゆ",r:"tsuyu",m:"국물/쓰유"},
    {h:"しちみ",k:"七味",r:"shichimi",m:"시치미 (7가지 양념 가루)"},
    {h:"こんとん",k:"混沌",r:"konton",m:"혼돈"},
    {h:"じゃどう",k:"邪道",r:"jadou",m:"사도/반칙"},
    {h:"こんぶ",k:"昆布",r:"konbu",m:"다시마"},
    {h:"いちみ",k:"一味",r:"ichimi",m:"이치미 (고춧가루)"},
    {h:"おおどおり",k:"大通り",r:"oodoori",m:"큰길/대로"},
    {h:"おでん",r:"oden",m:"오뎅/어묵탕"},
    {h:"いなりずし",k:"いなり寿司",r:"inarizushi",m:"유부초밥"},
    {h:"おやつ",r:"oyatsu",m:"간식"},
    {h:"かしわ",r:"kashiwa",m:"닭고기 (규슈 사투리)"},
    {h:"ぬくもり",r:"nukumori",m:"온기/따뜻함"},
    // 동사
    {h:"あげる",k:"揚げる",r:"ageru",m:"튀기다"},
    {h:"ひたす",k:"浸す",r:"hitasu",m:"적시다/담그다"},
    {h:"とける",k:"溶ける",r:"tokeru",m:"녹다/풀리다"},
    // 형용사·부사
    {h:"やわい",k:"柔い",r:"yawai",m:"부드러운 (구어)"},
    {h:"そぼく",k:"素朴",r:"soboku",m:"소박하다"},
    {h:"みっちり",r:"micchiri",m:"빽빽하게/가득"},
    {h:"もちもち",r:"mochimochi",m:"쫄깃쫄깃"},
    {h:"プラプラ",r:"purapura",m:"어슬렁어슬렁"},
  ];
WORD_DATA_MIKMAT[22] = { title: "11화 표현 (소년 마츠시게 소울푸드)", words: [
    {h:"全然違うんですよ",r:"zenzen chigaun desu yo",m:"완전 다르거든요"},
    {h:"使わないんだ",r:"tsukawanain da",m:"안 쓰는구나"},
    {h:"上京何歳だったんですか",r:"joukyou nansai dattan desu ka",m:"상경 몇 살이었어요?"},
    {h:"いいにおいするでしょ",r:"ii nioi suru desho",m:"좋은 냄새 나지?"},
    {h:"その場で作った",r:"sono ba de tsukutta",m:"그 자리에서 만든"},
    {h:"油で揚げて",r:"abura de agete",m:"기름에 튀겨서"},
    {h:"やってない",r:"yatte nai",m:"안 해요/없어요"},
    {h:"寂しいっすね",r:"sabishiissu ne",m:"쓸쓸하네요"},
    {h:"100円もない時は",r:"hyaku en mo nai toki wa",m:"100엔도 없을 때는"},
    {h:"白あんと黒あんですね",r:"shiroan to kuroan desu ne",m:"흰 앙금과 검은 앙금이네요"},
    {h:"やっぱ黒かな",r:"yappa kuro kana",m:"역시 검은 거부터지"},
    {h:"定番から",r:"teiban kara",m:"기본부터"},
    {h:"あんこがこれだけみっちり入ってて",r:"anko ga koredake micchiri haittete",m:"앙금이 이만큼 가득 들어있어서"},
    {h:"溶けちゃうでしょ",r:"tokechau desho",m:"녹아버리지?"},
    {h:"もちもちする感じ",r:"mochimochi suru kanji",m:"쫄깃쫄깃한 느낌"},
    {h:"これは絶品だ",r:"kore wa zeppin da",m:"이건 일품이다"},
    {h:"整形なんかしないでください",r:"seikei nanka shinaide kudasai",m:"성형 같은 거 하지 마세요"},
    {h:"食い応えがあるんですよ",r:"kuigotae ga arun desu yo",m:"든든하거든요"},
    {h:"ホテルで食べないでここで食べてた",r:"hoteru de tabenaide koko de tabeteta",m:"호텔에서 안 먹고 여기서 먹었어"},
    {h:"一日の始まりにする",r:"ichinichi no hajimari ni suru",m:"하루의 시작으로 하다"},
    {h:"入れた瞬間うんって",r:"ireta shunkan un tte",m:"넣은 순간 '음!' 하고"},
    {h:"素朴な味",r:"soboku na aji",m:"소박한 맛"},
    {h:"おばあさんのぬくもりの味だ",r:"obaasan no nukumori no aji da",m:"할머니의 따뜻한 맛이야"},
    {h:"混沌となってきたでしょ",r:"konton to natte kita desho",m:"혼돈스러워졌지?"},
    {h:"混沌になったスープがおいしい",r:"konton ni natta suupu ga oishii",m:"혼돈스러워진 국물이 맛있어"},
    {h:"ちょっと邪道だけど",r:"chotto jadou da kedo",m:"약간 반칙이지만"},
    {h:"おでん屋でスープくださいってよう言えない",r:"odenya de suupu kudasai tte you ienai",m:"오뎅집에서 국물 달라고 차마 못 해"},
    {h:"いなりずし1個だけもらえますか",r:"inarizushi ikko dake moraemasu ka",m:"유부초밥 하나만 주실래요?"},
    {h:"これは酒飲みが大喜びする味だ",r:"kore wa sakenomi ga ooyorokobi suru aji da",m:"이건 술꾼이 환장할 맛이야"},
    {h:"どうかしてる",r:"douka shiteru",m:"정신이 나갔어/미친 거 아니야"},
  ];
