// 미친맛집 시즌1 - 12화
WORD_DATA_MIKMAT[23] = { title: "12화 단어 (칼국수는 거들 뿐)", words: [
    // 명사
    {h:"カンナム",k:"江南",r:"kannamu",m:"강남 (지명)"},
    {h:"カルグクス",r:"karugukusu",m:"칼국수"},
    {h:"もはんいんしょくてん",k:"模範飲食店",r:"mohan inshokuten",m:"모범 음식점"},
    {h:"チヂミ",r:"chijimi",m:"부침개/전"},
    {h:"もりあわせ",k:"盛り合わせ",r:"moriawase",m:"모둠"},
    {h:"むしギョウザ",k:"蒸し餃子",r:"mushi gyouza",m:"찐 만두"},
    {h:"マンドゥ",r:"mandu",m:"만두"},
    {h:"スユク",r:"suyuku",m:"수육 (삶은 고기)"},
    {h:"チェユク",r:"cheyuku",m:"제육 (돼지고기 요리)"},
    {h:"ナクチポックム",r:"nakuchi pokkumu",m:"낙지볶음"},
    {h:"ブリスケ",r:"burisuke",m:"양지 (소 부위)"},
    {h:"せびろ",k:"背広",r:"sebiro",m:"정장 (구식 표현)"},
    {h:"ズッキーニ",r:"zukkinii",m:"애호박"},
    {h:"タラ",r:"tara",m:"대구 (생선)"},
    {h:"カキ",r:"kaki",m:"굴"},
    {h:"ジョン",r:"jon",m:"전 (한국식 부침)"},
    {h:"ヤンジ",r:"yanji",m:"양지 (소고기 최고급 부위)"},
    {h:"かいそう",k:"海藻",r:"kaisou",m:"해조류"},
    {h:"ぎゅうにく",k:"牛肉",r:"gyuuniku",m:"소고기"},
    {h:"えんぶん",k:"塩分",r:"enbun",m:"염분/짠기"},
    {h:"なまにんにく",k:"生にんにく",r:"nama ninniku",m:"생마늘"},
    {h:"そうめん",k:"素麺",r:"soumen",m:"소면"},
    {h:"ひかげん",k:"火加減",r:"hikagen",m:"불 조절"},
    {h:"たつじん",k:"達人",r:"tatsujin",m:"달인"},
    {h:"こんきょ",k:"根拠",r:"konkyo",m:"근거"},
    // 동사
    {h:"いためる",k:"炒める",r:"itameru",m:"볶다"},
    {h:"つける",r:"tsukeru",m:"찍다/담그다"},
    {h:"まとめる",r:"matomeru",m:"모으다/싸다"},
    // 형용사·부사
    {h:"ぜつみょう",k:"絶妙",r:"zetsumyou",m:"절묘하다"},
    {h:"ボッソボソ",r:"bossoboso",m:"퍽퍽한"},
    {h:"バキバキ",r:"bakibaki",m:"딱딱한/뻣뻣한"},
    {h:"あじわいぶかい",k:"味わい深い",r:"ajiwaibukai",m:"맛이 깊다/풍미가 깊다"},
  ];
WORD_DATA_MIKMAT[24] = { title: "12화 표현 (칼국수는 거들 뿐)", words: [
    {h:"こんだけお客さんがね",r:"kondake okyakusan ga ne",m:"이 정도로 손님이 많네"},
    {h:"親子3世代で来るんだ",r:"oyako san sedai de kurun da",m:"3대가 함께 오는구나"},
    {h:"牛肉ブリスケのだしですよ",r:"gyuuniku burisuke no dashi desu yo",m:"소고기 양지 육수예요"},
    {h:"ちゃんとしてるんだ",r:"chanto shiterun da",m:"제대로네"},
    {h:"いつもと違う",r:"itsumo to chigau",m:"평소와 다르잖아"},
    {h:"スーツはかっこいいんですよ",r:"suutsu wa kakkoiin desu yo",m:"정장은 멋있거든요"},
    {h:"知らないことが多すぎるなあ",r:"shiranai koto ga oosugiru naa",m:"모르는 게 너무 많구나"},
    {h:"結構塩分きついね",r:"kekkou enbun kitsui ne",m:"꽤 짜네"},
    {h:"うまみがいっぱい入ってる",r:"umami ga ippai haitteru",m:"감칠맛이 가득 들어있어"},
    {h:"自分が食べます",r:"jibun ga tabemasu",m:"제가 먹을게요"},
    {h:"ヤンジという一番高級な部位で",r:"yanji to iu ichiban koukyuu na bui de",m:"양지라는 최고급 부위로"},
    {h:"ほんとにミディアムレアっていうかさ",r:"honto ni midiamu rea tte iu ka sa",m:"진짜 미디엄 레어라고 할까"},
    {h:"これはうまい カキチヂミ",r:"kore wa umai kaki chijimi",m:"이거 맛있네, 굴전"},
    {h:"マッコリが合うっていう根拠って何だろうね",r:"makkori ga au tte iu konkyo tte nan darou ne",m:"막걸리가 어울린다는 근거가 뭘까"},
    {h:"この組み合わせが韓国の味",r:"kono kumiawase ga kankoku no aji",m:"이 조합이 한국의 맛"},
    {h:"韓国料理苦手っていう人でも",r:"kankoku ryouri nigate tte iu hito demo",m:"한국 요리 못 먹는다는 사람도"},
    {h:"マシッソッスムニダ",r:"mashissosumunida",m:"맛있었습니다 (한국어)"},
    {h:"マシッスムニダは今おいしいです",r:"mashissumunida wa ima oishii desu",m:"마시쓰무니다는 지금 맛있어요"},
    {h:"このタコはうまい",r:"kono tako wa umai",m:"이 낙지는 맛있다"},
    {h:"絶妙な火加減",r:"zetsumyou na hikagen",m:"절묘한 불 조절"},
    {h:"かなり達人ですよこれは",r:"kanari tatsujin desu yo kore wa",m:"상당한 달인이에요, 이건"},
    {h:"最高の状態でここに来たんですよ",r:"saikou no joutai de koko ni kitan desu yo",m:"최고의 상태로 여기에 온 거예요"},
    {h:"辛ってなる日本人結構いると思いますよ",r:"kara tte naru nihonjin kekkou iru to omoimasu yo",m:"'매워!'라고 하는 일본인 꽤 있을 거예요"},
    {h:"でも僕は大丈夫",r:"demo boku wa daijoubu",m:"하지만 난 괜찮아"},
    {h:"牛肉のスープですよ",r:"gyuuniku no suupu desu yo",m:"소고기 국물이에요"},
    {h:"だしの香りとか味わい深さとか",r:"dashi no kaori toka ajiwai bukasa toka",m:"육수의 향이나 깊은 맛이나"},
    {h:"おいしいね マシンネ",r:"oishii ne masinne",m:"맛있네 (일본어+한국어)"},
    {h:"アイラブユー",r:"ai rabu yuu",m:"아이 러브 유"},
  ];
