// 미친맛집 시즌1 - 13화
WORD_DATA_MIKMAT[25] = { title: "13화 단어 (곱창계의 에르메스)", words: [
    // 명사
    {h:"うし",k:"牛",r:"ushi",m:"소"},
    {h:"コプチャン",r:"kopuchan",m:"곱창"},
    {h:"マクチャン",r:"makuchan",m:"막창"},
    {h:"テッチャン",r:"tecchan",m:"대창"},
    {h:"ホルモン",r:"horumon",m:"호르몬 (내장 고기)"},
    {h:"ハツ",r:"hatsu",m:"염통 (심장)"},
    {h:"いぶくろ",k:"胃袋",r:"ibukuro",m:"위 (내장 부위)"},
    {h:"レバー",r:"rebaa",m:"간 (레버)"},
    {h:"もりあわせ",k:"盛り合わせ",r:"moriawase",m:"모듬"},
    {h:"つば",r:"tsuba",m:"침 (타액)"},
    {h:"しお",k:"塩",r:"shio",m:"소금"},
    {h:"しょうちゅう",k:"焼酎",r:"shouchuu",m:"소주"},
    {h:"あぶら",k:"脂",r:"abura",m:"기름/지방"},
    {h:"チャーハン",r:"chaahan",m:"볶음밥"},
    {h:"なべ",k:"鍋",r:"nabe",m:"전골/냄비"},
    {h:"なかみ",k:"中身",r:"nakami",m:"속/내용물"},
    {h:"のみかい",k:"飲み会",r:"nomikai",m:"술자리/회식"},
    {h:"キムチ",r:"kimuchi",m:"김치"},
    {h:"サラダ",r:"sarada",m:"샐러드"},
    {h:"あくじゅんかん",k:"悪循環",r:"akujunkan",m:"악순환"},
    {h:"ペース",r:"peesu",m:"페이스/속도"},
    {h:"プレッシャー",r:"puresshaa",m:"부담/압박"},
    {h:"かおり",k:"香り",r:"kaori",m:"향/향기"},
    {h:"わり",k:"割",r:"wari",m:"~할/비율"},
    {h:"なじみ",r:"najimi",m:"익숙함/단골"},
    {h:"ライス",r:"raisu",m:"밥/라이스"},
    // 동사
    {h:"わすれる",k:"忘れる",r:"wasureru",m:"잊다"},
    {h:"ふとる",k:"太る",r:"futoru",m:"살찌다"},
    {h:"にげる",k:"逃げる",r:"nigeru",m:"도망가다/빠지다"},
    {h:"つぐ",r:"tsugu",m:"(술을) 따르다"},
    {h:"よっぱらう",k:"酔っ払う",r:"yopparau",m:"취하다"},
    {h:"おもいしらせる",k:"思い知らせる",r:"omoishiraseru",m:"본때를 보여주다"},
    {h:"のます",k:"飲ます",r:"nomasu",m:"마시게 하다/먹이다"},
    // 형용사·부사
    {h:"はしたない",r:"hashitanai",m:"점잖지 못한/품위없는"},
    {h:"めんどうくさい",k:"面倒くさい",r:"mendoukusai",m:"귀찮다"},
    {h:"きのどく",k:"気の毒",r:"ki no doku",m:"불쌍한/안됐는"},
    {h:"うまれつき",k:"生まれつき",r:"umaretsuki",m:"태어날 때부터/선천적으로"},
    {h:"だんだん",r:"dandan",m:"점점/차차"},
  ];
WORD_DATA_MIKMAT[26] = { title: "13화 표현 (곱창계의 에르메스)", words: [
    {h:"初めての牛コプチャン",r:"hajimete no ushi kopuchan",m:"처음 먹는 소곱창"},
    {h:"つばが出てくる",r:"tsuba ga dete kuru",m:"침이 나오다"},
    {h:"はしたないな",r:"hashitanai na",m:"품위없네"},
    {h:"１個１個忘れていくんだよね",r:"ikko ikko wasurete ikun da yo ne",m:"하나하나 잊어가지"},
    {h:"香りがいいね",r:"kaori ga ii ne",m:"향이 좋네"},
    {h:"盛り合わせの中です",r:"moriawase no chuu desu",m:"모듬의 '중'입니다"},
    {h:"塩だけにつけて食べてもらいたい",r:"shio dake ni tsukete tabete moraitai",m:"소금만 찍어서 먹어봤으면 해요"},
    {h:"これは面白い食べ物です",r:"kore wa omoshiroi tabemono desu",m:"이건 재미있는 음식이에요"},
    {h:"なじみがある感じがするのよ",r:"najimi ga aru kanji ga suru no yo",m:"익숙한 느낌이 드는 거야"},
    {h:"マクチャンを選択",r:"makuchan wo sentaku",m:"막창을 선택"},
    {h:"悪循環 分かる分かる",r:"akujunkan wakaru wakaru",m:"악순환, 알아 알아"},
    {h:"焼酎を１本",r:"shouchuu wo ippon",m:"소주 1병"},
    {h:"合う合う",r:"au au",m:"어울려 어울려/맞아 맞아"},
    {h:"太れなかったね",r:"futorenakatta ne",m:"살 못 쪘네"},
    {h:"生まれつきですか？",r:"umaretsuki desu ka?",m:"타고난 건가요?"},
    {h:"空気で太る？",r:"kuuki de futoru?",m:"공기만으로 살찐다고?"},
    {h:"脂取られるだけのためのパン？",r:"abura torareru dake no tame no pan?",m:"기름 닦으려고만 쓰는 빵?"},
    {h:"気の毒なパン",r:"ki no doku na pan",m:"불쌍한 빵"},
    {h:"自分でつぐ 自分のペースで飲む",r:"jibun de tsugu jibun no peesu de nomu",m:"스스로 따르고, 자기 페이스로 마시다"},
    {h:"いろいろしてあげたい",r:"iroiro shite agetai",m:"이것저것 해주고 싶다"},
    {h:"プレッシャーかも",r:"puresshaa kamo",m:"부담일 수도"},
    {h:"酔っ払っちゃえ",r:"yopparacchae",m:"취해버려라"},
    {h:"７割ぐらいが基本かな",r:"nana wari gurai ga kihon kana",m:"7할 정도가 기본인가"},
    {h:"まだメニューにないんですけど",r:"mada menyuu ni nain desu kedo",m:"아직 메뉴에 없는 건데요"},
    {h:"中身ってどっか逃げたの？",r:"nakami tte dokka nigeta no?",m:"속이 어디 빠진 거야?"},
    {h:"中身が出てるから",r:"nakami ga deteru kara",m:"속이 나와 있으니까"},
    {h:"飲み会とかお好きですか？",r:"nomikai toka osuki desu ka?",m:"술자리 같은 거 좋아하세요?"},
    {h:"最初から最後まで",r:"saisho kara saigo made",m:"처음부터 끝까지"},
    {h:"だんだん増えてる",r:"dandan fueteru",m:"점점 올라가고 있어"},
    {h:"面倒くさいから",r:"mendoukusai kara",m:"귀찮으니까"},
    {h:"韓国の味 VS 日本の味",r:"kankoku no aji VS nihon no aji",m:"한국의 맛 vs 일본의 맛"},
    {h:"思い知らせなきゃ",r:"omoishirasenakya",m:"본때를 보여줘야지"},
  ];
